Scroll to top of comments
TeamNewPipe/NewPipe pull request #11654
Opened 2024-10-27 09:10 UTC by katalllen

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- addition of "scroll to top button"
- when clicked takes user to the top of the comments section

#### Before/After Screenshots/Screen Record

- Before:
![before](https://github.com/user-attachments/assets/05c944e0-8c60-47c2-acc7-8073bff45e12)

- After:
![newPipeAfter](https://github.com/user-attachments/assets/e2d0e018-5d06-4e8e-903e-2ce939e11ff8)

#### Fixes the following issue(s)

- Fixes #11036

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2024-10-27 12:31 UTC, katalllen commented
Hi @TobiGr, thank you so much for your quick reply. Yes I am an ANU student, I hope your thesis goes well :)

2024-10-27 16:29 UTC, Jean-BaptisteC commented
I prefer a fab with top arrow icon :)
https://m2.material.io/components/buttons-floating-action-button

2024-10-28 04:34 UTC, itsaky requested changes
A `FloatingActionButton` with an upward-facing arrow icon would be a better choice for this purpose. Also, the button could be hidden if the scroll position is already at the top of the list.

2024-10-28 04:34 UTC, itsaky commented on app/src/main/res/layout/fragment_comments.xml
> +        android:onClick="onClick"
The `onClick` attribute is redundant since you're using `setOnClickListener` to listen for click events.

2024-10-28 04:34 UTC, itsaky commented on app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
> +    private Button scrollToTopButton;
The `scrollToTopButton` is not referenced anywhere other than the `initViews` method. You should remove the field and make it a local variable instead.

2024-11-12 09:50 UTC, Stypox commented
NewPipe is currently in maintenance mode and is not accepting PRs for new features, especially niche features like this one. The refactor branch contains a scrollbar which is equivalent to having a "scroll to top" button, you can download an APK from here: https://github.com/TeamNewPipe/NewPipe-refactor-nightly

2024-11-12 09:50 UTC, closed without merging