Player UI list to kotlin
TeamNewPipe/NewPipe pull request #11829
Opened 2024-12-26 11:10 UTC by Profpatsch

Small helper module

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2024-12-26 14:47 UTC, Profpatsch commented
Okay I noticed a funny thing where threads would compete for modifying our UI list, so I added a Mutex around it.

2025-01-01 12:45 UTC, Profpatsch commented
The code quality thingy is mostly that I marked a function as deprecated and have not yet changed all use-sites because it’s not in-scope of this PR

2025-01-24 23:31 UTC, Isira-Seneviratne requested changes
This looks like a good change, overall.

2025-01-24 23:31 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +    }
```suggestion
    fun call(consumer: (PlayerUi) -> Unit) {
        // copy the list out of the mutex before calling the consumer which might block
        val new = playerUis.runWithLockSync {
            lockData.toMutableList()
        }
        for (ui in new) {
            consumer(ui)
        }
    }
```

2025-01-24 23:31 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +            return@runWithLockSync null
```suggestion
            lockData.firstNotNullOfOrNull { playerUiType.kotlin.safeCast(it) }
```

2025-01-24 23:31 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +    var playerUis = GuardedByMutex(mutableListOf<PlayerUi>())
[`Collections.synchronizedList()`](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedList-java.util.List-) could be used instead, which would remove the need for a separate mutex class.

```suggestion
    var playerUis = Collections.synchronizedList(mutableListOf<PlayerUi>())
```

2025-01-25 17:33 UTC, Stypox requested changes

2025-01-25 17:33 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +     </T> */
```suggestion
     * [Optional] otherwise
     */
```

2025-01-25 17:33 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +    }
Does this work even when called from Java?

2025-01-25 17:34 UTC, Stypox commented
The rest looks good to me, too, thanks!

2025-01-25 22:46 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +    }
Yeah, but Unit.INSTANCE has to be returned.

2025-01-25 23:33 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +        }
In combination with the above change:

```suggestion
    fun <T : PlayerUi> destroyAll(playerUiType: Class<T>) {
        // short blocking removal from class to prevent interfering from other threads
        val (toDestroy, toKeep) = synchronized(playerUis) {
            playerUis.partition { playerUiType.isInstance(it) }
        }
        playerUis.retainAll(toKeep)

        // then actually destroy the UIs
        for (ui in toDestroy) {
            ui.destroyPlayer()
            ui.destroy()
        }
```

2025-01-27 00:10 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
> +    }
I changed the parameter type back to `Consumer`; the synchronized list implementation automatically handles the synchronization needed.

2025-01-27 11:09 UTC, Profpatsch commented
@Isira-Seneviratne I don’t understand your review, you said this looks like a good change, but then you proposed to replace everything with SynchronizedList instead of using a Mutex?

2025-01-27 11:12 UTC, Isira-Seneviratne commented
> @Isira-Seneviratne I don’t understand your review, you said this looks like a good change, but then you proposed to replace everything with SynchronizedList instead of using a Mutex?

I meant that the idea of refactoring to ensure thread safety is a good one. Sorry if I caused any confusion.

2025-01-27 11:15 UTC, Profpatsch commented
Personally I don’t like the concept of a SynchronizedList very much, because you have to remember to only use it inside a `synchronized` block, otherwise you introduce bugs. But nothing will remind you to do that.

2025-01-27 11:45 UTC, Isira-Seneviratne commented
> Personally I don’t like the concept of a SynchronizedList very much, because you have to remember to only use it inside a `synchronized` block, otherwise you introduce bugs. But nothing will remind you to do that.

That's only when iterating through it without the Java forEach method. All other operations are synchronized.

2025-01-27 12:12 UTC, Profpatsch commented
Yeah, that makes it ever more devious!

2025-01-27 12:55 UTC, Profpatsch commented
So I’d rather not switch this from a simple Mutex around the list to `synchronizedList`, mainly because I don’t think having a partially thread-safe list really makes the implementation simpler, it’s just harder to reason about and easy to make mistakes.

2025-01-27 14:21 UTC, Stypox commented
Note: this conflicts with https://github.com/TeamNewPipe/NewPipe/pull/9592, so I'd rather merge it after that one is merged back in the refactor branch

2025-05-11 13:23 UTC, Profpatsch commented
Okay, since the new Android Auto PR was superseded (and the new one merged), I just rebased this and it still applies cleanly, so I think we can merge.

2025-05-13 21:36 UTC, Stypox approved these changes
I think some of Isira's suggestions apply even to the version marked with `Mutex`, but it's ok like it is now I think. Thank you!

2025-05-13 21:36 UTC, merged