Improve energy efficiency by applying Dynamic Retry Delay Energy Pattern + Cache Energy Pattern
TeamNewPipe/NewPipe pull request #3931
Opened 2020-07-24 15:19 UTC by anasofiagribeiro

This improves the energy efficiency of SecondScreen by applying the Dynamic Retry Delay Energy Pattern and the Cache Energy Pattern for mobile applications.

The energy pattern was applied in RouterActivity.java and AndroidManifest.xml (for the Dynamic Retry Delay Energy Pattern) and TLSSocketFactoryCompat.java (for the Cache Energy Pattern). The general idea for the first one is to avoid accessing an internet connection if the connection is down . In particular, a class NetworkStateReceiver will be created in the java file that checks for an internet connection. The general idea for the second one is to avoid performing unnecessary operations by using cache mechanisms. In particular, setting the cache size to have no limit.

2020-07-25 10:50 UTC, wb9688 commented
Please follow our code style, so that Checkstyle won't complain.

2020-07-29 11:48 UTC, Redirion commented
Sorry but this pattern appears to be outdated since Android 7, as the CONNECTIVITY_CHANGE cannot be received anymore from BroadcastReceivers registered in AndroidManifest.

Please see the Android doc: https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION

2020-09-17 17:19 UTC, anasofiagribeiro commented
Hello. I have a question, if Android version 7 has API Level 24 (https://source.android.com/setup/start/build-numbers), how come "registerDefaultNetworkCallback", that was added in API Level 24, doesn't work? Thank you for your time.

2020-11-11 18:37 UTC, anasofiagribeiro commented
Hello. Since the solution I proposed only works for Android 7 or newer, would a solution where this change only applies on Android 7 or newer be acceptable? This guarantees that for Android 7 or older it doesn’t break. 
“if (Build.VERSION.SDK_INT < 7 || hasActiveNetwork() ) {”

2020-11-17 09:11 UTC, Stypox commented
> would a solution where this change only applies on Android 7 or newer be acceptable?

Yes, that's the way to go, thank you ;-)

2020-11-17 12:18 UTC, Redirion commented on app/src/main/java/org/schabi/newpipe/RouterActivity.java
> +            if (Build.VERSION.SDK_INT < 7 || hasActiveNetwork()) {
```suggestion
            if (Build.VERSION.SDK_INT < 24 || hasActiveNetwork()) {
```

2020-11-20 16:25 UTC, Stypox requested changes
It doesn't build because of checkstyle, see https://travis-ci.org/github/TeamNewPipe/NewPipe/builds/716366001
Also, could you further explain what you did? Is it safe to put the ssl cache to infinity? And are we sure we want to do nothing silently when the user shares something to NewPipe until the connection is active (if I understood correctly that's what the code does)?

2020-11-20 16:25 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/RouterActivity.java
> +                    preferences.edit();
Why `.edit()`?

2020-11-23 08:42 UTC, Redirion commented on app/src/main/java/org/schabi/newpipe/RouterActivity.java
> +                    preferences.edit();
```suggestion
```
unintente obviosly

2021-06-13 09:25 UTC, mhmdanas commented
@anasofiagribeiro  I'm closing this PR, but please make a comment when you want to resume work on this so I would re-open it. Thanks!

2021-06-13 09:25 UTC, closed without merging