Format all XML resources
TeamNewPipe/NewPipe pull request #4471
Opened 2020-10-09 18:26 UTC by wb9688

#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Format all XML resources using Ctrl+Alt+l in Android Studio. I've also manually added newlines at the end of XML resources that currently didn't have a newline.

#### Fixes the following issue(s)
Seeing stuff like https://github.com/TeamNewPipe/NewPipe/pull/4453/files#diff-8093b831702ba14428d2d99c9edded66 in PRs, which makes it harder to review.

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

2020-10-09 20:31 UTC, avently commented
Finally. THANK YOU.

2020-10-10 10:56 UTC, connectety commented
Nice work.
IMO this PR should add xml-linting to make sure the work will not be undone in like a year.
I mean this can always be checked in the review, but that will often mean an extra commit and might be just forgotten.

2020-10-10 15:09 UTC, wb9688 commented
@connectety: That was also what I was thinking, however I'm not aware of a way to run Android Studio's XML formatter from the command line.

2020-10-11 09:22 UTC, Stypox requested changes
Can we just assume `Ctrl+Alt+L` does his job correctly and merge directly? ;-)
345 files are too many to check ;-)

Anyway, I took a brief look and there does not seem to be any strange things. I'm not sure if we would need to do some deeper analysis or we can just trust AS. Maybe we can so something like [this](https://stackoverflow.com/questions/3978068/how-to-check-if-the-two-xml-files-are-equivalent-with-python)?

2020-10-11 09:22 UTC, Stypox commented on app/src/main/res/layout/player_notification.xml
>  <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Oh, seems like I forgot to remove the old notification layout

2020-10-11 09:22 UTC, Stypox commented on app/src/main/res/layout/player_notification_expanded.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Also here, could you remove them while you are at it?

2020-10-11 09:39 UTC, wb9688 commented
@Stypox: It's just some XML, I'd trust Android Studio for that. Also from taking a quick look at what it did (for the first about 100 files).

2020-10-11 09:48 UTC, wb9688 commented
Fwiw the source code of Android Studio's XML formatter is at https://android.googlesource.com/platform/tools/base/+/refs/tags/studio-4.0.0/sdk-common/src/main/java/com/android/ide/common/xml/

2020-10-11 12:45 UTC, Stypox submitted a review, later dismissed
Ok, then @TobiGr merge

2020-10-14 00:00 UTC, TacoTheDank commented
You have no idea how happy this makes me.

2020-10-14 07:16 UTC, opusforlife2 commented
@TacoTheDank You do seem like the kind of person who likes a well-kept codebase. 🤭

2020-10-14 10:38 UTC, Stypox commented
For some reason the Synk vulnerability checks are failing, but I don't have the rights to access the results and find out why

2020-10-14 11:35 UTC, TobiGr approved these changes

2020-10-14 11:36 UTC, TobiGr commented
snyk is also failing for other PRs. There are no dependency changes in this PR, so this should be good to merge.

2020-10-14 11:36 UTC, merged