Loading screen improvement
TeamNewPipe/NewPipe pull request #4938
Opened 2020-11-20 20:56 UTC by okan35

#### What is it?
- [ ] Bugfix (user facing)
- [x ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world
Currently when we refresh what's new, we see only loading screen on main screen with number of videos loading and at the same time we can see this on notification. I removed loading screen from main screen so while app is loading new videos, we can also browse and watch videos.We should not be waiting for videos to finish loading so we can watch video or check what we have in list of videos, this definitely was not a good idea so I changed this. While videos load we can still check the content. And if the someone wants to see number of videos that are loading, he/she can do so by checking the notification.

#### Fixes the following issue(s)

- 

#### Relies on the following changes

- 

#### APK testing 

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5576033/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2020-11-21 04:00 UTC, B0pol commented
I really dislike this behaviour.

The loading screen is there to show the user it's loading and it's not frozen.

Now you don't know the progress, it refreshes when it's loaded and really feels "wow it didn't work, I'm going to press refresh button again" with about 50 subs.

On top of that, it seems you didn't read contribution guidelines, because you don't follow them

> Send PR that only cover one specific issue/solution/bug. Do not send PRs that are huge and consists of multiple
independent solutions

2020-11-21 06:37 UTC, okan35 commented
I now see where you are coming from because if you click to refresh the feed it shows like there is nothing going on. But if you pull to refresh it shows you a loading icon until the process is done. 

We can also add that small icon so people dont pull to refresh bit click to refresh can see what is going on.

As to issue part, this actually was in #3329, you can see my comment and I don't know why it was closed as the requests in that issue were not done yet and only implemented small part of it which is pull to refresh.

Also instead of opening new issue I added mine in the same issue as it is covered under improvement of refresh.

2020-11-21 09:45 UTC, opusforlife2 commented
@okan35 We now strictly follow a policy of "one idea per issue/PR". So you can just open a new issue, describe the problem this PR is solving, and link it to this PR.

2020-11-21 11:49 UTC, okan35 commented
> @okan35 We now strictly follow a policy of "one idea per issue/PR". So you can just open a new issue, describe the problem this PR is solving, and link it to this PR.

I just did that and later will add the progress dialogue  or icon whatever for click refresh, pull to refresh already does that.

2020-11-21 17:30 UTC, opusforlife2 commented
@okan35 You can use keywords to link a PR to an issue. https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

2020-11-21 17:37 UTC, okan35 commented
> 
> 
> @okan35 You can use keywords to link a PR to an issue. https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Will do it next time, didn't know this existed.

2020-11-21 17:56 UTC, okan35 commented
Added the necessary change for showing loading icon on click to refresh. I believe the feature is done now.

2020-12-12 14:11 UTC, Stypox requested changes
I like this, though I am not sure if it is a good idea not to show any progress indicator except for the hard-to-access notification. You could show the loading bar, which previously was shown at the center of the screen, just below the `Feed last updated: ...` bar at the top. Also, please remove all comments, they are not needed anymore. Thank you for this contribution that would decrease time waste :-D

2020-12-12 14:11 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +        animateView(items_list, true, 0)
There is no need for this, i.e. to show `items_list`, if you never hide it ;-)

2020-12-12 14:11 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +        swipeRefreshLayout.isRefreshing=false
No need for this, it is already inside `hideLoading()`

2020-12-13 14:38 UTC, okan35 commented
> 
> 
> I like this, though I am not sure if it is a good idea not to show any progress indicator except for the hard-to-access notification. You could show the loading bar, which previously was shown at the center of the screen, just below the `Feed last updated: ...` bar at the top. Also, please remove all comments, they are not needed anymore. Thank you for this contribution that would decrease time waste :-D

I pushed the changes for those reviews you left. I would suggest that we do that feature of showing progress of video fetching in another pull request.  But it is a good idea to show it like that, below feed last updated when user refreshes video list, and when it finishes we can hide it back,

2020-12-14 18:47 UTC, Stypox requested changes
> I would suggest that we do that feature of showing progress of video fetching in another pull request.

Yeah, ok, but both PRs need to ship in the same release, otherwise we are taking away the progress indicator from users, which would be cumbersome. Are you willing to make another PR right after this one?

2020-12-14 18:47 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> -}
Add back the newline at the end of the file (checkstyle should have complained)

2020-12-14 18:47 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> -    // /////////////////////////////////////////////////////////////////////////
Bring back these comments.. sorry if I was unclear, I meant that old code shouldn't be commented-out but directly removed. But useful comments like this should be kept.

2020-12-14 20:08 UTC, okan35 commented
I can make another pr but I will do it around this week as it is a matter of time :D

2020-12-19 15:04 UTC, okan35 commented
I added that progress text below video last fetched and those comments are back as I went to that commit. Updated the apk. To me it looked nice as it shows up with progress and disappears when it is finished.

2021-01-14 21:50 UTC, Stypox reviewed
Could you rebase?

2021-01-14 21:50 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> -    // /////////////////////////////////////////////////////////////////////////
Bring back these comments ;-)

2021-10-01 17:40 UTC, litetex commented
Closing this for now:
* no progress
* no GitHub actions build
* merge conflicts
* Snyk Found vulnerabilities!
* No feedback from the author

Feel free to reopen it when there is progress again.

2021-10-01 17:40 UTC, closed without merging