Readme.fr
TeamNewPipe/NewPipe pull request #5107
Opened 2020-12-06 13:54 UTC by B0pol

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (user facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world
Translate README
#### Fixes the following issue(s)

- 

#### Relies on the following changes

- 

#### APK testing 

debug.zip

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

I still need to fix navigation links, but that will be easier with GitHub

2020-12-06 13:58 UTC, mhmdanas commented
I'm making a PR to fix #5051, so I think you should wait until it is merged so that you can translate what I added too.

2020-12-06 21:17 UTC, pihug12 requested changes
There are some typos.

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +* Chosir le lecteur permettant de regarder des vidéos
```suggestion
* Choisir le lecteur permettant de regarder des vidéos
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +* Ovurir une vidéo dans Kodi
```suggestion
* Ouvrir une vidéo dans Kodi
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +Lorsque des modifications sont effectués au code de NewPipe (soit grâce à de nouvelles nouveautés, soit à cause de corrections de bugs), une mise à jour finira par être disponible. Le format de versi
```suggestion
Lorsque des modifications sont effectuées au code de NewPipe (soit grâce à de nouvelles nouveautés, soit à cause de corrections de bugs), une mise à jour finira par être disponible. Le format de version est x.xx.x . Pour obtenir les nouvelles versions, vous pouvez :
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> + 3. Télécharger depuis un fichier APK depus les [publications GitHub (releases)](https://github.com/TeamNewPipe/NewPipe/releases) et installez l'appli. Les mises à jour seront disponibles dès qu'elle
```suggestion
 3. Télécharger un fichier APK depuis les [publications GitHub (releases)](https://github.com/TeamNewPipe/NewPipe/releases) et installez l'appli. Les mises à jour seront disponibles dès qu'elles sont publiées par l'équipe NewPipe.
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> + 4. Metre à jour via F-Droid. C'est la méthode la plus lente, puisque F-Droid doit être compiler et créer un fichier APK, le signer, puis publier la mise à jour à ses utilisateurs.
```suggestion
 4. Mettre à jour via F-Droid. C'est la méthode la plus lente, puisque F-Droid doit compiler l'application, signer l'APK, puis publier la mise à jour à ses utilisateurs.
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +Par conséquent, notre appli ne collecte rien sans votre consentement. La poliique de confidentialité de NewPipe explique en détail quelles données sont envoyées et conservées lorsque vous signaler un
```suggestion
Par conséquent, notre appli ne collecte rien sans votre consentement. La politique de confidentialité de NewPipe explique en détail quelles données sont envoyées et conservées lorsque vous signalez une erreur, ou commentez sur notre blog. Vous pouvez trouver ce document [ici](https://newpipe.net/legal/privacy/).
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +telle que publiée par la Free Software Foundation , soit la version 3 de la Licence, soit (à votre gré) toute version ultérieure.
```suggestion
telle que publiée par la Free Software Foundation, soit la version 3 de la Licence, soit (à votre gré) toute version ultérieure.
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +Si vous aimeriez contribuer, veuiller regarder nos [notes de contribution](.github/CONTRIBUTING.md).
```suggestion
Si vous aimeriez contribuer, veuillez regarder nos [notes de contribution](.github/CONTRIBUTING.md).
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +Que ce soit pour des idées, des traductions, des changement de design, une amélioration du code ou un changement majeur du code, de l'aide est toujours appréciée.
```suggestion
Que ce soit pour des idées, des traductions, des changements de design, une amélioration du code ou un changement majeur du code, de l'aide est toujours appréciée.
```

2020-12-06 21:17 UTC, pihug12 commented on README.fr.md
> +3. Téléchargez NewPipe depuis la nouvelle source et installer le
```suggestion
3. Téléchargez NewPipe depuis la nouvelle source et installer l'application
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> + 3. Télécharger depuis un fichier APK depus les [publications GitHub (releases)](https://github.com/TeamNewPipe/NewPipe/releases) et installez l'appli. Les mises à jour seront disponibles dès qu'elle
```suggestion
 3. Télécharger un fichier APK depuis les [publications GitHub (releases)](https://github.com/TeamNewPipe/NewPipe/releases) et installer l'appli. Les mises à jour seront disponibles dès qu'elles sont publiées par l'équipe NewPipe.
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +<b>METTRE NEWPIPE OU N'IMPORTE QUEL FORK SUR LE GOOGLE PLAY STORE VIOLE LEUR CONDITIONS GÉNÉRALES D'UTILISATION.</b>
```suggestion
<b>METTRE NEWPIPE OU N'IMPORTE QUEL FORK SUR LE GOOGLE PLAY STORE VIOLE LEURS CONDITIONS GÉNÉRALES D'UTILISATION.</b>
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +Nous recommendons la méthode 2 à la plupart de nos utilisateurs. Les fichiers APK installés via la méthode 2 ou 3 sont compatibles, mais pas avec la méthode 4. Nous utilisons notre signature pour sig
```suggestion
Nous recommandons la méthode 2 à la plupart de nos utilisateurs. Les fichiers APK installés via la méthode 2 ou 3 sont compatibles, mais pas avec la méthode 4. Nous utilisons notre signature pour signer les fichiers APK, mais F-Droid utilise sa propre signature. La création d'un APK via la méthode 1 exclut entièrement une signature. Android compare les signatures lors des mises à jour pour des raisons de sécurité, c'est pourquoi ces méthodes sont incompatibles.
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +<b>AVERTISSEMENT : C'EST UNE VERSION BETA, PAR CONSÉQUENT VOUS POURRIEZ RENCONTRER DES BUGS. SI C'EST LE CAS, VEUILLEZ OUVRIR UN TICKET VIA NOTRE DÉPÔT GITHUB.</b>
```suggestion
<b>AVERTISSEMENT : C'EST UNE VERSION BÊTA, PAR CONSÉQUENT VOUS POURRIEZ RENCONTRER DES BOGUES. SI C'EST LE CAS, VEUILLEZ OUVRIR UN TICKET VIA NOTRE DÉPÔT GITHUB.</b>
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +Lorsque des modifications sont effectués au code de NewPipe (soit grâce à de nouvelles nouveautés, soit à cause de corrections de bugs), une mise à jour finira par être disponible. Le format de versi
```suggestion
Lorsque des modifications sont effectuées au code de NewPipe (soit grâce à de nouvelles nouveautés, soit à cause de corrections de bogues), une mise à jour finira par être disponible. Le format de version est x.xx.x . Pour obtenir les nouvelles versions, vous pouvez :
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +* Regarder les vidéos d'une chaine
```suggestion
* Afficher des informations générales à propos des chaînes
* Rechercher des chaînes
* Regarder les vidéos d'une chaîne
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +* S'abonner à des chaines
```suggestion
* S'abonner à des chaînes
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +Cependant, si vous voulez changer de source pour certaines raisons (par ex. une fonctionnalité principale de NewPipe ne fonctionne plus et F-Droid n'a pas encore publié la mise à jour), nous vous rec
```suggestion
Cependant, si vous voulez changer de source pour certaines raisons (par ex. une fonctionnalité principale de NewPipe ne fonctionne plus et F-Droid n'a pas encore publié la mise à jour), nous vous recommandons cette procédure :
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +1. Sauvegardez vos données via les Paramètres > Contenu -> Exporter la base de donnée, afin de conserver les abonnements, listes de lecture et l'historique
```suggestion
1. Sauvegardez vos données via les Paramètres > Contenu -> Exporter la base de données, afin de conserver les abonnements, les listes de lecture et l'historique
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +3. Téléchargez NewPipe depuis la nouvelle source et installer le
```suggestion
3. Téléchargez NewPipe depuis la nouvelle source et installez l'application
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +Si vous aimez NewPipe, nous serions heureux de recevoir un don. Vous pouvez soit donner avec des bitcoin ou via Bountysource ou Liberapay. Pour plus d'informations, veuillez visiter notre [site web](
```suggestion
Si vous aimez NewPipe, nous serions heureux de recevoir un don. Vous pouvez soit donner avec des bitcoins, soit via Bountysource ou soit via Liberapay. Pour plus d'informations, veuillez visiter notre [site web](https://newpipe.net/donate).
```

2020-12-13 13:36 UTC, TiA4f8R commented on README.fr.md
> +Le projet NewPipe cherche a fournir une expérience anonyme et privée pour les services multimédias en ligne.
```suggestion
Le projet NewPipe cherche à fournir une expérience anonyme et privée pour les services multimédias en ligne.
```

2020-12-29 17:37 UTC, XiangRongLin requested changes

2020-12-29 17:37 UTC, XiangRongLin commented on README.fr.md
> +<a href="https://travis-ci.org/TeamNewPipe/NewPipe" alt="État de compilation"><img src="https://travis-ci.org/TeamNewPipe/NewPipe.svg"></a>
This need to be replaced with the github badge.
see #5278

2021-01-15 18:58 UTC, TobiGr requested changes

2021-01-15 18:58 UTC, TobiGr commented on README.fr.md
> +*Read this in other languages: [English](README.md), [Français](README.fr.md), [한국어](README.ko.md).*
the newly added translations need to linked

2021-06-18 16:36 UTC, closed without merging

2021-06-18 16:46 UTC, B0pol commented on README.fr.md
> +* Regarder les vidéos d'une chaine
On n’est pas obligé https://fr.wiktionary.org/wiki/chaine