Update README.md to include installation methods other than F-Droid
TeamNewPipe/NewPipe pull request #5108
Opened 2020-12-06 14:05 UTC by mhmdanas

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [X] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- [X] Update "updates" section to account for F-Droid bug
- [ ] Include other methods of installation (maybe add a new section?)
- [ ] (Maybe) remove the F-Droid badge

@B0pol what do you think I should do exactly?

#### Fixes the following issue(s)

-  Fixes #5051

#### APK testing 

Unnecessary.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-01-03 13:38 UTC, kujaw commented
Isn't installing NewPipe Legacy also one of temporary solutions? 
I've just installed it and it works. Additionally I don't have to install any repo or download apk from the website.

2021-01-14 21:47 UTC, Stypox commented
@mhmdanas is this ready?

2021-01-14 22:11 UTC, mhmdanas commented
@Stypox no. I totally forgot about this PR. I'll finish it tomorrow.

2021-01-15 15:28 UTC, mhmdanas commented
Done. You can review now.

2021-01-15 17:40 UTC, Stypox requested changes
I like this, thank you for looking into it
<sub>When will F-Droid solve the issue?!?!?</sub>

2021-01-15 17:40 UTC, Stypox commented on README.md
> +## Installation
Maybe "Installation and updates"?

2021-01-15 19:20 UTC, mhmdanas commented on README.md
> +## Installation
Done.

2021-01-15 19:40 UTC, Stypox approved these changes

2021-01-15 19:45 UTC, TobiGr approved these changes

2021-01-15 19:46 UTC, merged

2021-01-15 19:46 UTC, TobiGr commented
We need a list of README translators, so we can ping them when changing the English version and the changes can be applied to the other READMEs as fast as possible.

2021-01-15 19:50 UTC, Stypox commented
Can't READMEs be pushed to Weblate?