(need help) Cover image feature
TeamNewPipe/NewPipe pull request #6278
Opened 2021-05-13 10:15 UTC by mangoepic

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- add cover image to downloaded files
- maybe add title and artist metadata later

#### Fixes the following issue(s)

- Fixes #5445
- Fixes #4341

#### Relies on the following changes

- Change in the Download Preferences
- Change in the Download Dialogue
- Change in the Download Manager <--- HERE i need help, where should the code get implemented? how can i use the file that gets downloaded in the code?

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-05-13 10:21 UTC, mhmdanas commented
Please don't change the README; it's unrelated to your changes.

2021-05-13 10:23 UTC, mhmdanas requested changes

2021-05-13 10:23 UTC, mhmdanas commented on app/src/main/res/values/strings.xml
> +    <string name="download_cover_preference">cover_pref_key</string>
This particular line should go in `settings_keys.xml`, and you should set `translatable="false"` on it.

2021-06-07 08:36 UTC, Stypox commented
@mangoepic this can't be done without adding `ffmpeg`, see the discussion in #5445

2021-06-07 08:36 UTC, closed without merging