fix long uploader name which results in not seeing service name in bo…
TeamNewPipe/NewPipe pull request #6287
Opened 2021-05-14 09:49 UTC by aliraad79

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- add a new function in PlaylistRemoteEntity 
- use the upper function in RemotePlaylistItemHolder 

#### Fixes the following issue(s)
- Fixes #4924 

#### APK testing 
- I don't get this part :)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-05-14 11:03 UTC, SameenAhnaf commented
I think, you should place name and details of channel, playlists and videos in this way. Place the thumbnail in the middle for list and make the text scrolling for grid view.
![IMG_20210514_170033](https://user-images.githubusercontent.com/79245641/118262067-30d1f800-b4d6-11eb-963e-bb9e79a83c4f.jpg)

![IMG_20210514_170043](https://user-images.githubusercontent.com/79245641/118262101-3af3f680-b4d6-11eb-8e78-06bb88648e02.jpg)

2021-05-15 04:11 UTC, opusforlife2 commented
@aliraad79 Please edit your issue body to reflect what the PR is _doing_, instead of just listing the code changes you made. Those are fine to mention in the details, but they can't be the only thing in your description.

Also, the issue title is too long and is also cut off. Please make it shorter.

2021-05-15 13:44 UTC, mhmdanas requested changes

2021-05-15 13:44 UTC, mhmdanas commented on app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistRemoteEntity.java
> +        return uploader.substring(0, Math.min(uploader.length(), 35)) + "...";
If I'm not mistaken, this will always show the ellipsis, which is definitely not something that we want.

2021-05-15 16:31 UTC, aliraad79 commented
Thanks for all of your fast comments. I fix this things in a new commit

2021-05-16 01:02 UTC, opusforlife2 commented
@aliraad79 Thanks. Could you add a couple of screenshots to show how it looks now?

2021-06-08 09:16 UTC, Stypox commented
This has to be fixed by changing the layout and setting `ellipsize`, not by truncating the string with code.

2021-10-02 15:28 UTC, litetex commented
I'm closing this PR for now:
* no progress
* This should be fixed in the UI not in the code: https://github.com/TeamNewPipe/NewPipe/pull/6287#issuecomment-856604658
* Code has problems as pointed out in https://github.com/TeamNewPipe/NewPipe/pull/6287#discussion_r632951375

Feel free to reopen it when there is further progress.

2021-10-02 15:28 UTC, closed without merging