Resolve Tabs style checks
TeamNewPipe/NewPipe pull request #6346
Opened 2021-05-22 04:49 UTC by Imericxu

#### What is it?

- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Clean up equals methods
- Add hashCode methods matching respective equals to resolve style check warnings

#### APK testing 

On the website, the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence

- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-05-22 14:07 UTC, Imericxu commented
I see that my pull request has a lot more commits than other people’s; should I squash them?

2021-06-06 21:31 UTC, Stypox commented
@Imericxu no, that's ok

2021-06-08 12:44 UTC, Stypox requested changes
Looks mostly good, thank you!

2021-06-08 12:44 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
> +            return playlistServiceId == other.playlistServiceId // Remote
Let's keep it consistent
```suggestion
            return super.equals(obj)
                    && playlistServiceId == other.playlistServiceId // Remote
```

2021-06-08 12:44 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
>              }
```suggestion
```

2021-06-08 12:49 UTC, Stypox approved these changes
There are now only three checkstyle warnings. Great :-)

2021-06-08 12:49 UTC, merged