Prevent recaptcha webview from keeping youtube loaded in background
TeamNewPipe/NewPipe pull request #6733
Opened 2021-07-22 01:39 UTC by Douile

After the cookies are extracted from the recaptcha webview make it load an empty page to prevent youtube being loaded unecessarily in the background.

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Load empty page in recaptcha webview after youtube is no longer needed

#### Fixes the following issue(s)

- Fixes #6732 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-07-22 06:14 UTC, Stypox requested changes

2021-07-22 06:14 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java
> +        recaptchaBinding.reCaptchaWebView.loadData("", "text/html", null);
According to [this SO](https://stackoverflow.com/questions/3715482/how-to-clear-webview-content) you should use
```suggestion
        recaptchaBinding.reCaptchaWebView.loadUrl("about:blank");
```

2021-07-24 13:46 UTC, nadiration commented
Thank you for doing this! This is specially useful on limited data plans

2021-07-24 17:57 UTC, Stypox approved these changes

2021-07-27 09:41 UTC, merged

2021-07-27 09:41 UTC, Stypox commented
Thank you!