Fix Settings import
TeamNewPipe/NewPipe pull request #7169
Opened 2021-09-25 10:33 UTC by laksh-21

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- The "Search Suggestions" setting in Settings > Content > Search Suggestions is a MultiSelectListPreference and that exports as a HashSet of all the enabled options.
- The export was going through properly but the import function did not have a case to handle when value in the key, value pair is a HashSet
- Since the incoming value was not being processed, they were just reverting back to their default values.
- I have added the case to handle when value is a HashSet. 
- The Supress annotation was added because value is of type any? and it needs to be converted to MutableSet<String>? which throws a Unchecked Cast warning. As far as I know, this warning can be suppressed without any problems because the HashSet will always be convertible to MutableSet<String>. 

#### Fixes the following issue(s)

- Fixes  #7075

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

Also, this is my first time contibuting :). Can I get a feedback on how well this OR description was writted?

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-09-26 15:10 UTC, opusforlife2 commented
Hi, @laksh-21, and thank you for contributing to Newpipe! I think your PR description was well written. I made some small edits to make it look better, which you can see in detail using the edit history.

2021-09-26 19:05 UTC, laksh-21 commented
@opusforlife2 oh thanks! I'll keep that in mind next time. Didn't realize I made so many types T_T.
By the way, does the review usually take a long time?

2021-09-26 19:12 UTC, opusforlife2 commented
@laksh-21 That completely depends on developer availability. Since this is a completely voluntary project, that could mean hours/days/weeks or even months. But usually small PRs like yours get reviewed fairly quickly.

2021-09-26 19:57 UTC, litetex requested changes
Code generally looks good to me (LGTM)

However I request some minor changes.

Tested this (with my minor changes) and works as expected ✔️

2021-09-26 19:57 UTC, litetex commented on app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
> +                        is HashSet<*> -> {
```suggestion
                        is Set<*> -> {
```
Set exactly matches the type of ``putStringSet`` - so let's use it.

2021-09-26 19:57 UTC, litetex commented on app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
> +                            @Suppress("UNCHECKED_CAST")
```suggestion
                            // There are currently only Sets with type String possible
                            @Suppress("UNCHECKED_CAST")
```

Adding a comment here why the warning is ignored

2021-09-26 19:57 UTC, litetex commented on app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
> +                            preferenceEditor.putStringSet(key, value as MutableSet<String>?)
```suggestion
                            preferenceEditor.putStringSet(key, value as Set<String>?)
```
Set exactly matches the type of ``putStringSet`` - so let's use it.

2021-09-26 20:17 UTC, laksh-21 commented
Hi @litetex I've made the requested changes :)

2021-09-27 18:28 UTC, litetex approved these changes
LGTM

2021-09-27 21:42 UTC, merged