Update changelog
TeamNewPipe/NewPipe pull request #7476
Opened 2021-11-30 21:32 UTC by litetex

Updated the changelog for #7473

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-11-30 21:36 UTC, TobiGr submitted a review, later dismissed

2021-12-01 19:58 UTC, mhmdanas requested changes

2021-12-01 19:58 UTC, mhmdanas commented on fastlane/metadata/android/en-US/changelogs/980.txt
> +• Added "Add to playlist" open to share menu
```suggestion
• Added "Add to playlist" option to share menu
```

2021-12-01 20:04 UTC, mhmdanas approved these changes

2021-12-01 20:06 UTC, merged