Fix download dialog selector layout
TeamNewPipe/NewPipe pull request #7516
Opened 2021-12-08 14:09 UTC by mauriciocolli

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Some logic was missing in the adapter for making the no-audio icon  `GONE` instead of `INVISIBLE`. I fixed it and added some tests as well.

<img src="https://user-images.githubusercontent.com/13389907/145215374-de9081f5-b3d7-4935-8e03-67e1cbb16fd6.png" width=250>

That reveals another problem: some icons are not themed properly, I will fix that in another pull request.
<img src="https://user-images.githubusercontent.com/13389907/145216828-e96319e1-6897-4f3e-9721-e30c1b91b1ef.png" width=250>

#### Fixes the following issue(s)
- Fixes #6677

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2021-12-08 19:47 UTC, litetex requested changes
Code looks on the first impression good.
👍 for the tests

However I would appreciate some (there is currently zero) documentation like JavaDoc or comments.

2021-12-10 16:38 UTC, mauriciocolli commented
Done.

2021-12-12 14:02 UTC, litetex reviewed
LGTM

However I'm unable to get a situation where the icon is visible in the first place.

@mauriciocolli 
Do you know a situation/video where that's the case?

2021-12-12 14:02 UTC, litetex commented on app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
> +    private boolean checkHasVideoOnlyWithNoSecondaryStream() {
I would rename that method to ``checkHasAnyVideoOnlyStreamWithNoSecondaryStream``

2022-04-02 13:50 UTC, litetex commented
* Rebased the PR
* Applied changes
* Fixed tests
* The UI works now as expected:
Modified - for testing purposes (because I couldn't find any stream that has no audio) - ``hasSecondaryStream`` so that it always returns ``false`` :
![grafik](https://user-images.githubusercontent.com/40789489/161386241-a7671846-40f0-48e6-8b2c-ec6f3459a607.png) ![grafik](https://user-images.githubusercontent.com/40789489/161386258-f3b5a83b-ecf8-4b7b-9cad-b9fb2239ca20.png)

2022-04-02 13:52 UTC, litetex approved these changes

2022-04-02 14:04 UTC, merged