Added loading of items when the view can't be scrolled
TeamNewPipe/NewPipe pull request #7638
Opened 2022-01-09 21:38 UTC by AbduAmeen

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added loading of items when scrolling isn't possible for classes implementing BaseListFragment class.

#### Before/After Screenshots/Screen Record

#### Fixes the following issue(s)

- Fixes #1974

#### Relies on the following changes

#### APK testing 

Comment: 
- I ran into the bug #4475 several times when I was testing the grid view on a tablet emulator. I just wanted to make you aware of that. 

- I didn't know how to test the local list 
#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-01-10 09:17 UTC, mhmdanas requested changes

2022-01-13 21:32 UTC, litetex reviewed
Thank you for the PR 😄 

It seems to work but:
* ~this seems to work just by sheer luck:~
![grafik](https://user-images.githubusercontent.com/40789489/149405312-76e81e48-bd9f-4926-af5c-8d4a854f911e.png)
I don't know who designed an API that calls onScrolled when no scroll event occurs...
* This will be called whenever a scroll occurs - that can be quite resource intensitive

Let's have a look at the problem:
So there is not enough data initially loaded.

Then I think we should load enough data initially:
* initially load the data
* if there is more data loadable and the view is not scrollable → load more data
* repeat above if needed
 
I will try to create a PR for my mentioned resolution this week.

2022-01-14 22:20 UTC, litetex requested changes
Sorry but I have to block the PR:
Tested the PR again - on a tablet and with grid mode - and the search crashes in >60% of all cases:

https://user-images.githubusercontent.com/40789489/149587288-a6440283-0218-47bd-9733-41c51871e397.mp4

PS: I'm still working on the PR but I run into some unexpected errors when using RecyclerView which might be related to #4475

2022-01-16 18:46 UTC, litetex commented
Superseded by #7659 

Anyway thank you for the work 😄

2022-01-16 18:46 UTC, closed without merging