Fix first item always played in the play queue when reloading play queue manager and set player recovery in more places
TeamNewPipe/NewPipe pull request #7693
Opened 2022-01-24 10:21 UTC by TiA4f8R

#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

This PR fixes the playback of the first item in the play queue when a resolution (when switching the quality played in the quality selector) or a player type change occurs (for e.g. switching from background to main player), when playing another item than the first one of the play queue.

The issue was caused by an ExoPlayer change, which when setting a new media source, resets now the current playback position and the current window index to the first item and its default position by default (the position was then set with the first item's recovery position).

It sets now to ExoPlayer to not reset the position when setting a new media source.

This PR also sets the player recovery in more places to fix playback position not propely set in some cases after a player type switch (in other words: the fix of #7668 is applied in more places).

#### Fixes the following issue(s)
- Fixes #7531

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-01-24 19:20 UTC, litetex requested changes
#7427 was already fixed.
What are the ``player.setRecovery`` blocks doing inside this PR?

2022-01-24 20:02 UTC, TiA4f8R commented
See https://github.com/TeamNewPipe/NewPipe/issues/7427#issuecomment-985465982: the player recovery position needs to be set when clicking on the content thumbnail (so playback position is not lost when you used background or popup player (by pressing the background button) and you are now using main player).

Other additions are for cases like this one: you put the app with a content playing in the main player on the background, so background player is used while the player is not visible and you came back to the player with Android's media notification. Playback position was not saved and the content starts to play again from the previous playback position saved (I was able to reproduce this once, now it seems I can't).

2022-01-24 20:21 UTC, litetex commented
@TiA4f8R 
And how is that related to #7531?

Please one bugfix at the time if they aren't directly linked together.
We could have fixed #7531 by now if these were 2 PRs.

It would be best if you limit this PR to the fixes of #7531 and create a new PR for the additional fixes of #7427.

Btw: I think the workaround for #7427 is incomplete because in ![grafik](https://user-images.githubusercontent.com/40789489/150858159-fd6f026e-3b34-4dc1-9699-d38556d47a37.png) the workaround should also be applied to ``overlay_metadata_layout`` and ``overlay_buttons_layout``

2022-01-24 20:42 UTC, TiA4f8R commented
> the workaround should also be applied to `overlay_metadata_layout` and `overlay_buttons_layout`

In fact, no, because there is no need to set player recovery when pressing an element inside the metadata part of the description or when pressing other buttons than popup and background buttons.

> It would be best if you limit this PR to the fixes of #7531 and create a new PR for the additional fixes of #7427.

Ok, if you want.

2022-01-25 10:45 UTC, Stypox approved these changes
According to the [documentation](https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L1164-L1172) what you did is correct, and that's the only place where `setMediaSource` is used.
I tested on API 19 emulated, API 31 emulated and API 29 device and the fix worked (i.e. I could reproduce the bug before, but with the same steps now I can't).

2022-01-25 18:54 UTC, litetex approved these changes
LGTM

Nice and simple 👍

2022-01-25 18:55 UTC, merged