german README.de.md
TeamNewPipe/NewPipe pull request #7979
Opened 2022-03-02 16:51 UTC by Spleezzer

german translation

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

I have created a german translation for the README.md

#### Fixes the following issue(s)

- Fixes: German tranlation README.md

#### APK testing 

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-03-02 19:26 UTC, litetex requested changes
Thank you for the PR.

Found these major problems:
* Images are not loading/link are wrong
* Nearly every line contains a spelling mistake
* The other Readme's need references to this one

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> + 4. Erstelle eine Debug-APK für dich. Dies ist die schnellste Methode, um neue Aktualisierungen zu bekommen, aber auch die komplizierteste. Wir empfehlen daher eine der anderen Methoden.
```suggestion
 4. Erstelle selber eine Debug-APK. Dies ist die schnellste Methode um neue Aktualisierungen zu bekommen, aber auch die komplizierteste. Wir empfehlen daher eine der anderen Methoden.
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> + 3. Aktualisierungen mit F-Droid. Dies ist die langsamste von allen Methoden, da F-Droid die Änderungen erkennen, die APK von selbst erstellen, unterzeichnen, und dann für die Benutzer veröffentliche
```suggestion
 3. Aktualisierung via F-Droid Dies ist die langsamste von allen Methoden, da F-Droid die Änderungen erkennen, die APK von selbst erstellen, signieren und dann für die Benutzer veröffentlichen muss.
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> + 1. Füge ein eigenes Repository bei F-Droid hizu. Die Anweisungen findest du hier: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/
```suggestion
 1. Füge unser Repository bei F-Droid hinzu. Die Anweisungen gibt es hier: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +NewPipe unterstützt diverse Dienste. Unsere [docs](https://teamnewpipe.github.io/documentation/) Unsere Dokumente enthalten weitere Informationen darüber, wie ein neuer Dienst zur App und zum Extrakt
```suggestion
NewPipe unterstützt diverse Dienste. Unsere [Dokumentation](https://teamnewpipe.github.io/documentation/) enthält weitere Informationen darüber, wie ein neuer Dienst zur App und zum Extraktor hinzugefügt werden kann. Bitte kontaktiere uns, wenn du einen Neuen hinzufügen möchtest. Die aktuell unterstützten Dienste sind:
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Kommentare werden angezeigt
```suggestion
* Kommentare
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Lokale Playlisten
```suggestion
* Lokale Playlists
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Warteschlangen
```suggestion
* Videos hintereinander wiedergeben
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Suche und abspielen von Playlists
```suggestion
* Suchen und abspielen von Playlists
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Schaue Videos von einem Kanal aus
```suggestion
* Schaue Videos von einem Kanal an
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +<b>DAS HOCHLADEN VON NEWPIPE VERSTÖSST GEGEN DIE ALLGEMEINEN GESCHÄFTSBEDINGUNGEN.</b>
```suggestion
<b>DAS HOCHLADEN VON NEWPIPE VERSTÖẞT GEGEN DIE NUTZUNGSBEDINGUNGEN.</b>
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +<b>WARNUNG: DIES IST EINE BETA-VERSION, DAHER KÖNNEN BUGS AUFTRETEN. WENN DU AUF WELCHE TRIFFST, ÖFFNE EIN ISSUE AUF DIESEM GITHUB REPOSITORY.</b>
```suggestion
<b>WARNUNG: DIES IST EINE BETA-VERSION, DAHER KÖNNEN UNERWARTETE PROBLEME AUFTRETEN. WENN DU AUF WELCHE TRIFFST, ÖFFNE EIN ISSUE IN DIESEM GITHUB REPOSITORY.</b>
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +<p align="center"><a href="#screenshots">Screenshots</a> &bull; <a href="#description">Description</a> &bull; <a href="#features">Fuktionen</a> &bull; <a href="#installation-and-updates">Installation
```suggestion
<p align="center"><a href="#screenshots">Screenshots</a> &bull; <a href="#description">Beschreibung</a> &bull; <a href="#features">Funktionen</a> &bull; <a href="#installation-and-updates">Installation und Aktualisierungen</a> &bull; <a href="#contribution">Beitrag</a> &bull; <a href="#donate">Spende</a> &bull; <a href="#license">Lizenz</a></p>
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +<p align="center"><a href="https://f-droid.org/packages/org.schabi.newpipe/"><img src="https://fdroid.gitlab.io/artwork/badge/get-it-on-en.svg" alt="Get it on F-Droid" height=80/></a></p>
Use the german version of the image please:
```suggestion
<p align="center"><a href="https://f-droid.org/packages/org.schabi.newpipe/"><img src="https://fdroid.gitlab.io/artwork/badge/get-it-on-de.svg" alt="Get it on F-Droid" height=80/></a></p>
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +Wir empfehlen Methode 1 für die meisten Nutzer. APKs die mit Methode 1 oder 2 installiert wurden sind miteinander kompatibel, aber nicht mit denen von Methode 3. Dies liegt daran, dass derselbe Signa
```suggestion
Wir empfehlen Methode 1 für die meisten Nutzer. APKs die mit Methode 1 oder 2 installiert wurden sind miteinander kompatibel, aber nicht mit denen von Methode 3. Dies liegt daran, dass derselbe Signaturschlüssel (unserer) für 1 und 2 verwendet wird, aber ein anderer Signaturschlüssel (F-Droid) für 3 verwendet wird. Beim Erstellen einer Debug-APK mit Methode 4 wird ein Schlüssel vollständig ausgeschlossen. Signaturschlüssel tragen dazu bei, dass ein Benutzer nicht dazu verleitet wird ein schädliches Update für eine App zu installieren.
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +Wenn Sie in der Zwischenzeit aus irgendeinem Grund die Quellen wechseln möchten (z. B. die Kernfunktionalität von NewPipe bricht und F-Droid hat noch nicht das neueste Update), empfehlen wir Ihnen, d
```suggestion
Wenn du in der Zwischenzeit aus irgendeinem Grund die Quellen wechseln möchten (z. B. NewPipe funktioniert nicht korrekt und F-Droid hat noch nicht das neueste Update), empfehlen wir, dieses Verfahren zu befolgen:
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +Je mehr getan wird, desto besser wird es!
```suggestion
Egal ob du Ideen, Übersetzungen, Designänderungen, Codebereinigung oder wirklich schwerwiegende Codeänderungen hast: Hilfe ist immer willkommen. Je mehr getan wird, desto besser wird es!
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +Wenn du NewPipe magst, würden wir uns über eine Spende freuen. Du kannst entweder Bitcoin schicken oder über Bountysource oder Liberapay spenden. Für weitere Informationen über Spenden an NewPipe bes
```suggestion
Wenn du NewPipe magst, würden wir uns über eine Spende freuen. Du kannst entweder Bitcoin senden oder über Bountysource oder Liberapay spenden. Für weitere Informationen über Spenden an NewPipe besuche bitte unsere [Website](https://newpipe.net/donate).
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +(nach Ihrer Wahl) jede spätere Version.
```suggestion
NewPipe ist eine freie Software: Du kannst sie benutzen, studieren, teilen, und verbessern wie du magst. Insbesondere kannst du es weitergeben und/oder modifizieren unter den Bedingungen der [GNU General Public License](https://www.gnu.org/licenses/gpl.html) wie veröffentlicht von der Free Software Foundation, entweder in Version 3 der Lizenz, oder (nach Ihrer Wahl) jede spätere Version. 
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +Daher sammelt die App keine Daten ohne Ihre Zustimmung. In der Datenschutzerklärung von NewPipe wird detailliert erläutert, welche Daten gesendet und gespeichert werden, wenn Sie einen Unfallbericht
```suggestion
Das NewPipe-Projekt zielt darauf ab eine private, anonyme Erfahrung bei der Nutzung von Medien-Webdiensten zu ermöglichen. Daher sammelt die App keine Daten ohne Ihre Zustimmung. In der Datenschutzerklärung von NewPipe wird detailliert erläutert, welche Daten gesendet und gespeichert werden, wenn du einen Fehlerbericht sendest oder in unserem Blog kommentierst kannst du [hier](https://newpipe.net/legal/privacy/) finden.
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +* Wählen Sie den Streaming-Player aus, mit dem Sie Videos ansehen möchten
```suggestion
* Wähle selber den Streaming-Player aus, mit dem du Videos ansehen möchtest
```

2022-03-02 19:26 UTC, litetex commented on doc/README.de.md
> +*Lese dieses Dokument in anderen Sprachen: [English](README.md), [Deutsch](doc/README.de.md), [Español](doc/README.es.md), [한국어](doc/README.ko.md), [Soomaali](doc/README.so.md), [Português Brasil](do
I think this should be moved to a new line (and centered) as there are too many languages in one line

2022-03-30 19:06 UTC, litetex commented
No feedback since over 1 month :/

Closing this for now.

2022-03-30 19:06 UTC, closed without merging

2022-07-25 19:16 UTC, lebogg commented
I already started with a translation as well and now saw this closed pull request. I would finish it while also incorporating your comments on this previous attempt @litetex ?

2022-07-25 19:20 UTC, opusforlife2 commented
@lebogg You're most welcome to. :D