Fix Videos can't have "watched" status and/or "Remove watched" doesn't work and/or "playback position" feature is bugged #7563
TeamNewPipe/NewPipe pull request #8259
Opened 2022-04-19 16:36 UTC by LingYinTianMeng

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Before fixing, in the playlist view press "Remove watched', then press "OK", no videos are removed. After fixing, all completely watched videos can be removed.

#### Before/After Screenshots/Screen Record

- Before:

https://user-images.githubusercontent.com/95514488/164049714-6f9da584-5dd1-400e-ba61-277526fc481d.mp4

- After:

https://user-images.githubusercontent.com/95514488/164049736-921ddd74-4249-4a25-b2ab-7141bd03db87.mp4

#### Fixes the following issue(s)

- Fixes #7563 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-04-19 19:29 UTC, Coder246 approved these changes

2022-05-02 14:08 UTC, Stypox requested changes
Thank you! I forgot about this when I improved how stream states are saved

2022-05-02 14:22 UTC, LingYinTianMeng commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
>                                  notWatchedItems.add(playlistItem);
I think it is    indexInHistory < 0 || (streamStateEntity != null && !streamStateEntity.isFinished(duration)),  there should be 
a "!" before streamStateEntity.isFinished(duration)

2022-05-02 19:06 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
>                                  notWatchedItems.add(playlistItem);
Ooops, yes, you are right

2022-05-03 01:39 UTC, LingYinTianMeng commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
>                                  notWatchedItems.add(playlistItem);
OK, I have modified it.

2022-05-05 16:02 UTC, Stypox requested changes

2022-05-05 16:03 UTC, Stypox requested changes
Spaces should be kept. Other than that, thanks :-)

2022-05-05 16:03 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
>                          while (playlistIter.hasNext()) {
```suggestion

                        while (playlistIter.hasNext()) {
```

2022-05-05 16:03 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
> +                            if (indexInHistory < 0 || (streamStateEntity != null
```suggestion

                            if (indexInHistory < 0 || (streamStateEntity != null
```

2022-05-05 16:08 UTC, Stypox approved these changes

2022-05-05 16:08 UTC, merged