Added higher resolutions to the default res settings when they are enabled
TeamNewPipe/NewPipe pull request #8263
Opened 2022-04-20 07:29 UTC by Coder246

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

Added higher resolutions the the default resolution settings.
They are only visible, when show higher resolutions are turned on.

When the user has selected a higher resolution as default and he turns "show higher resolutions" off, the highest now available resolution will be used as a fallback.

#### Before/After Screenshots/Screen Record
- Before:
![Screenshot_20220420-092024_NewPipe Debug](https://user-images.githubusercontent.com/46609883/164173213-c5a2dc7e-4a64-444e-af9b-9b604d8028c6.jpg)
- After:
![Screenshot_20220420-092033_NewPipe Debug](https://user-images.githubusercontent.com/46609883/164173233-ff1b0dd2-2378-4ba2-acfa-bfd395a5db4f.jpg)

#### Fixes the following issue(s)
- Fixes   #2941 

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-04-22 15:34 UTC, litetex requested changes
Didn't review it in detail but had a quick look:
There are serious formatting and code style problems

Example:
```java
    private void updateResolutions() {


        if (getPreferenceManager().getSharedPreferences()
                .getBoolean(getString(R.string.show_higher_resolutions_key), false)) {

            //if setting was turned on, enable additional resolutions
            showHigherResolutions(true);

        } else {

            showHigherResolutions(false);


        }
    }
```

I'm also pretty sure that not all fields are required

2022-04-22 15:46 UTC, Coder246 commented
You don't allow lines longer than 100 characters.
What is the preferred way to deal with them?

2022-04-24 13:53 UTC, litetex commented
> You don't allow lines longer than 100 characters.
> What is the preferred way to deal with them?

Uhm using a new line?

2022-04-24 15:12 UTC, Coder246 commented
Then everything should be fine.
I simply used a new line when i run out of characters.

2022-04-24 15:19 UTC, litetex commented
@Coder246 
Not sure what you are talking about but the above method alone has at least the following problems:
* way to many empty new lines
* The comment is formatted incorrectly
* The if block is useless, this can be done inline

2022-04-24 15:21 UTC, opusforlife2 commented
Isn't code formatting enforced by a linter? And what about Checkstyle?

2022-04-24 15:26 UTC, closed without merging