Fixed viewed counting
TeamNewPipe/NewPipe pull request #8336
Opened 2022-05-02 13:21 UTC by Mamadou78130

#### What is it?
- [ X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [ X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-05-02 14:27 UTC, Stypox requested changes
Thank you! What a simple change :-)

2022-05-02 14:27 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntity.java
> +        this(streamUid, accessDate, 0);
```suggestion
        this(streamUid, accessDate, 0); // start with 0 views (adding 1 will be done elsewhere)
```

2022-05-04 17:19 UTC, litetex approved these changes

2022-05-04 17:33 UTC, merged

2022-06-10 12:52 UTC, litetex commented
@TiA4f8R 
I think this works as expected: You want to watch something but you didn't watch it yet → 0 views but inside the history.

Anyway, could you open a new issue for that, so we can discuss it there? :)

2022-06-10 13:12 UTC, TiA4f8R commented
@litetex Sorry, I think I wasn't clear in my comment, that's why you misunderstood my sentence: this happens when they are enqueued and after they have been played, so it is a regression.

Free feel to open an issue yourself about this regression :)

2022-07-01 14:17 UTC, Stypox commented
@Mamadou78130 see #8564 for an actual fix, but thank you anyway for this PR :-)