Add dialog for deletion in playlist.
TeamNewPipe/NewPipe pull request #8351
Opened 2022-05-04 12:46 UTC by samyberkane04

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Add dialog for deleting video in playlist.

#### Fixes the following issue(s)
Fix #7845

2022-05-06 08:30 UTC, Stypox requested changes

2022-05-06 08:30 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
>          if (playlistManager.getPlaylistThumbnail(playlistId)
All of the actions below should also be done only if the user really wants the item to be removed

2022-05-06 08:30 UTC, Stypox commented on app/src/main/res/values/strings.xml
> +    <string name="confirm_video_deletion_from_local_playlists">Are you sure to delete ?</string>
Keep style with other similar questions throughout newpipe: 
```suggestion
    <string name="confirm_video_deletion_from_local_playlists">Do you want to remove this item?</string>
```

2022-05-06 08:30 UTC, Stypox requested changes

2022-05-06 08:30 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
> -
Readd this line

2022-05-11 19:33 UTC, litetex commented
I would also favor @Redirion proposal.

2024-03-28 15:21 UTC, closed without merging