Use tint methods.
TeamNewPipe/NewPipe pull request #8405
Opened 2022-05-16 08:26 UTC by Isira-Seneviratne

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use tint methods to set drawable colors.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-05-22 20:02 UTC, Stypox commented
What is the advantage of using these methods instead of `PorterDuffColorFilter`?

2022-06-03 03:11 UTC, TacoTheDank commented
Hmm, this doesn't seem necessary in light of the coming support removal for APIs < 21. Opinions?

2022-07-08 08:24 UTC, Isira-Seneviratne commented
> > Opinions?
> 
> This depends on whether we drop support for API 19 in 0.24.0 (spoiler: YES!) or not. 
> 
> > What is the advantage of using these methods instead of PorterDuffColorFilter?
> 
> Answer is awaiting ;-)

The PorterDuff mode does not need to be specified when setting the tint (the default is SRC_IN).

2022-07-14 20:04 UTC, Stypox requested changes

2022-07-14 20:04 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/Player.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
Please remove these checks, as now the minsdk is lollipop (21), then this PR is ready

2022-07-15 06:02 UTC, TacoTheDank commented
Could you rebase the PR (on dev) and force-push to only have one commit? That will make it much easier to read :)

2022-07-18 21:24 UTC, Stypox requested changes
It doesn't seem to work correctly: the top image is the color of the seekbar before this PR, the bottom one is from this PR.
![image](https://user-images.githubusercontent.com/36421898/179619505-51e27927-9274-4144-9804-7197755d93d5.png)
![image](https://user-images.githubusercontent.com/36421898/179619559-a8391d87-af61-4eb6-8062-466b1cd4cc0c.png)

2022-07-18 21:24 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
> +                .WHITE));
```suggestion
        binding.progressBarLoadingPanel.setIndeterminateTintList(
                ColorStateList.valueOf(Color.WHITE));
```

2022-07-19 02:36 UTC, TacoTheDank commented
Sorry for being annoying lol, but I'd like to request another rebase for readability :P

2022-07-20 10:00 UTC, Stypox commented
Now it seems to work as it should but... why does commit 763f0bf7ab31f3e7badb621c71cd4c8e83ffc086 solve the problem? I mean, why does `setThumbTintList` do the correct thing while `setProgressTintList` doesn't, requiring you to use `getProgressDrawable().setTint`? I still have some doubts about this PR, since it doesn't seem to provide better code than before (I mean, what was wrong with specifying `PorterDuff` mode?) but seems to introduce possibility for bugs.

2022-07-23 06:31 UTC, Isira-Seneviratne commented
I undid a couple of the changes.

2022-07-25 21:14 UTC, Stypox commented
I'm sorry, I have to reject this pull request. The original code calls `setColorFilter`, while the proposed code calls (I delved into library code) `setTintList` on the same `Drawable`. The two functions behave similarly, according to the [documentation](https://developer.android.com/reference/android/graphics/drawable/Drawable#setTintList(android.content.res.ColorStateList)), but there appear to be some differences, and I don't want to risk having non-working code. Also, [this Stack Overflow](https://stackoverflow.com/questions/56716093/setcolorfilter-is-deprecated-on-api29#56717316) thread suggests the differences actually are there.

2022-07-25 21:14 UTC, closed without merging