Feature/local play
TeamNewPipe/NewPipe pull request #8514
Opened 2022-06-15 13:24 UTC by gcandrade10

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-06-15 15:16 UTC, mhmdanas requested changes
Can you clarify the PR title a bit? I believe this PR implements local file playback, but the title isn't exactly clear on that. Also, please fill out the PR template.

2022-06-15 15:16 UTC, mhmdanas commented on app/build.gradle
> +//}
Same here.

2022-06-15 15:16 UTC, mhmdanas commented on app/build.gradle
> +//    preDebugBuild.dependsOn runCheckstyle, runKtlint
Ditto.

2022-06-15 15:16 UTC, mhmdanas commented on app/src/main/java/us/shandian/giga/service/DownloadManager.java
> +    public DownloadManager(@NonNull Context context, Handler handler, StoredDirectoryHelper storageVideo, StoredDirectoryHelper storageAudio) {
Apologies if it's obvious, but why was this made public?

2022-06-15 15:16 UTC, mhmdanas commented on foo.patch
> +From 6d1eee441f3051c730cc4b51294bc83fcc1d156e Mon Sep 17 00:00:00 2001
Please remove this file.

2022-06-15 15:16 UTC, mhmdanas commented on gradle/wrapper/gradle-wrapper.properties
> +zipStoreBase=GRADLE_USER_HOME
What's the purpose behind these changes?

2022-06-15 18:03 UTC, TobiGr requested changes
Thank you for PR. please fill in the template and add comments to your code explaining the general purpose of methods and if needed, what they do specifically. This makes the review process easier for us and keeps the code somewhat maintainable in the future.

2022-06-19 22:08 UTC, opusforlife2 commented
Didn't we reject local file playback as 'out of scope'?

2022-06-19 22:18 UTC, opusforlife2 commented
Since there is a contributor willing to maintain this feature, I think a 'wait and see' approach could be taken. What is important is for the feature to work _without_ breaking, within whatever scope is decided to be adopted for it.

For example, the feature could be highly limited to only playing back a single file from the SAF file browser, like file browsing apps themselves often do.

Or it could create a folder within the app directory (as a narrow option) or somewhere else on the filesystem (as a broader option) and manage and play files within that directory/folder.

And then there are even bigger scopes, of course. It could ask the user to mark folders to watch for media, and keep track of file addition/removal/modification.

@gcandrade10 I have no idea what your PR does right now. Please fill out the template properly.

2022-07-16 12:55 UTC, litetex commented
No feedback from the author since a month - seems to be a fire and forget PR.

And btw this PR is violating our statement from https://github.com/TeamNewPipe/NewPipe/issues/478.

Closing.

2022-07-16 12:55 UTC, closed without merging

2022-07-26 03:20 UTC, Sepero commented
It's reality unfortunate to see submissions like this be dismissed. NewPipe is a great YouTube frontend, but it's also a great Video Player in general. It would be great if NewPipe could play local videos (even if only supports a few formats like mp4 and webm). I actually much prefer NewPipe's interface over VLC

2022-07-26 19:14 UTC, opusforlife2 commented
@Sepero https://newpipe.net/FAQ/#bugs-play-downloaded-videos