Modified empty_subscription_feed_subtitle to improve discoverability of the subscription import/export menu
TeamNewPipe/NewPipe pull request #8566
Opened 2022-07-01 22:50 UTC by Poslovitch

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Changed the default value for `empty_subscription_feed_subtitle` string key
- Removed all translations for this key (as requested in #8508)

#### Before/After Screenshots/Screen Record

- Before:
![](https://user-images.githubusercontent.com/36421898/168053706-046374ea-129a-40b0-8d77-735cb32a8c15.png)
- After: 
![image](https://user-images.githubusercontent.com/20014332/176975485-723ab97f-008a-4c0a-85ca-20e17f6add25.png)

#### Fixes the following issue(s)

- Fixes #8504 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-03 18:08 UTC, litetex requested changes
I think we need a few changes:
1. Somehow "empty_subscription_feed_subtitle" is used inside ``list_empty_view.xml`` which is used nearly everywhere and not just in the subscription area:
![grafik](https://user-images.githubusercontent.com/40789489/177052034-626e4f64-e8ae-4de1-ae4f-9702505dba26.png)
2. The layout is not correctly aligned
3. See the comment below

2022-07-03 18:08 UTC, litetex commented on app/src/main/res/values/strings.xml
> +    <string name="empty_subscription_feed_subtitle">You can import and export subscriptions from the three-dot menu</string>
```suggestion
    <string name="empty_subscription_feed_subtitle">You can import and export subscriptions using the three-dot menu</string>
```

2022-07-14 20:35 UTC, foss-enjoyer commented
That's way too long. "Import & export subscriptions from 3-dot menu." would fit better.

2022-10-12 15:38 UTC, Poslovitch commented
I'm getting back on working on this PR. Please pardon the long delay.

2022-12-04 18:29 UTC, Stypox commented
Since I couldn't push to this PR (you probably forbade pushes to this branch by maintainers), I opened #9501 instead. Thanks anyway!

2022-12-04 18:29 UTC, closed without merging