Checkstyle assign on same line
TeamNewPipe/NewPipe pull request #8601
Opened 2022-07-10 12:26 UTC by litetex

#### What is it?
- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR
See https://github.com/TeamNewPipe/NewPipe/pull/8170#discussion_r917278123.

After some discussion with @Stypox  a while ago (can't find the issue/PR anymore :/ ) where to put the ``=`` on a new line or not we agreed to put it not on the next line.

This PR was create to enforce this behavior.

This PR also removes some unused code that was found on the fly.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-13 16:42 UTC, Stypox requested changes
LGTM, except for the unused code removal. Thanks ;-)

2022-07-13 16:42 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/urlfinder/PatternsCompat.java
>  package org.schabi.newpipe.util.urlfinder;
I don't think you can just remove things from this file at random. This file was taken from AOSP and modified, as the licence explains (though a comment would be better), so any change should be documented I guess.

2022-07-14 04:10 UTC, TacoTheDank commented on app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
> +            BASE_ACTION + "ACTION_RECREATE_NOTIFICATION";
You could probably just remove the newlines for most of these 🤔

2022-07-14 07:08 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
> +            BASE_ACTION + "ACTION_RECREATE_NOTIFICATION";
I think they are this way for alignment purposes... I'd leave them this way

2022-07-15 06:03 UTC, TacoTheDank commented on app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
> +            BASE_ACTION + "ACTION_RECREATE_NOTIFICATION";
¯\_(ツ)_/¯ alrighty

2022-07-18 14:38 UTC, Stypox approved these changes
Thanks :-)

2022-07-18 14:39 UTC, merged