Fix errors in README.md
TeamNewPipe/NewPipe pull request #8618
Opened 2022-07-13 02:04 UTC by Rauf00

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The README.md contains some grammatical errors and can be made more concise.

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-13 11:00 UTC, mhmdanas commented
Thanks for the PR, but it seems like a lot of the changes aren't "error" fixes, but just subjective rewordings? Also, do please fill out the PR template.

2022-07-13 11:05 UTC, mhmdanas requested changes

2022-07-13 11:05 UTC, mhmdanas commented on README.md
> +If you like NewPipe, you're welcome to donate. We prefer Liberapay, as it is both open-source and non-profit. For further info on donating to NewPipe, please visit our [website](https://newpipe.net/d
I can't quite put my finger on why, but I prefer the original wording.

2022-07-16 12:51 UTC, litetex commented
Please fill out the template accordingly and reopen the PR when done so.

2022-07-16 12:51 UTC, closed without merging

2022-07-17 15:15 UTC, opusforlife2 commented
Not only are some of the suggestions grammatically incorrect, some of them are removing important information. So I'm disinclined to accept this PR as it is.

You can come discuss with us in Newpipe's IRC about what changes you would like to see. It's pretty difficult to debate grammar through PR reviews.