Removed the "(beta)"-tag from services
TeamNewPipe/NewPipe pull request #8637
Opened 2022-07-16 14:37 UTC by litetex

#### What is it?
- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR
Some time ago we removed the "beta"-tag from all services inside the Readme.
This PR adjusts the app accordingly.

I'm also not sure why there ever was a (beta) flag inside the services as all services are in theory beta (even YT) because we can't guarantee that they are stable as we don't control the remote side.

#### Before/After Screenshots/Screen Record
![grafik](https://user-images.githubusercontent.com/40789489/179358179-6059e499-a932-4fdc-b1d1-8d7f3a57c883.png)

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-17 15:20 UTC, mhmdanas approved these changes
LGTM

2022-07-17 15:24 UTC, mhmdanas requested changes
Actually, the UI changes do LGTM, but there's a code smell reported by Sonar (the `s` parameter of `enhancePeertubeMenu` is not used anymore and should be removed).

2022-07-24 12:38 UTC, litetex commented
@mhmdanas 
Done

2022-07-24 12:56 UTC, mhmdanas approved these changes

2022-07-24 12:57 UTC, merged