Use IO extensions.
TeamNewPipe/NewPipe pull request #8648
Opened 2022-07-18 01:12 UTC by Isira-Seneviratne

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use Kotlin's IO extensions.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-20 08:55 UTC, Stypox requested changes
Nice, thanks

2022-07-20 08:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
> +            throw IllegalArgumentException("Could not get license file: " + license.filename, e)
```suggestion
            throw IllegalArgumentException("Could not get license file: ${license.filename}", e)
```

2022-07-20 22:59 UTC, TacoTheDank commented
@Stypox Nice commit name :P

2022-07-22 16:29 UTC, Stypox approved these changes
I tested and it works fine. Thanks

> Nice commit name :P

Mmmh?

2022-07-22 16:30 UTC, merged