Create README.ru.md
TeamNewPipe/NewPipe pull request #8711
Opened 2022-07-30 16:38 UTC by ViktorOn

Changes:

- Added translation to Russian language of the file README

2022-08-04 14:48 UTC, mhmdanas requested changes
Please add a link to the Russian README to all the READMEs, _

2022-08-04 14:48 UTC, mhmdanas commented on doc/README.ru.md
> +
There's no point in having this if the README is brand new:
```suggestion
```

2022-08-04 14:48 UTC, mhmdanas commented on doc/README.ru.md
> +*Эта страница на других языках: [English](README.md), [Español](doc/README.es.md), [हिन्दी](doc/README.hi.md), [한국어](doc/README.ko.md), [Soomaali](doc/README.so.md), [Português Brasil](doc/README.pt_
Please add a link to the Russian README to the end of this line, here and in all the other READMEs.

2022-08-11 15:05 UTC, mhmdanas reviewed
I went ahead resolved my review myself. LGTM now.

2022-08-11 17:20 UTC, ViktorOn commented
@mhmdanas Oh, that's great news. I've been busy, so it's good that you solved this issue.

2023-07-17 20:08 UTC, closed without merging

2023-07-17 20:10 UTC, TobiGr commented
Thank you for your work. Your changes were merged in #10240