Use ListAdapter.
TeamNewPipe/NewPipe pull request #8719
Opened 2022-07-31 10:26 UTC by Isira-Seneviratne

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use [`ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) to handle displaying list data in `PeertubeInstanceListFragment` and `SuggestionListAdapter`.

#### Before/After Screenshots/Screen Record

- Before:
https://user-images.githubusercontent.com/31027858/182021881-f60beea1-e880-42f8-a9d2-173b8ea8f72d.mp4
- After:
https://user-images.githubusercontent.com/31027858/182021890-30818b27-d39d-43d5-91d0-8d041227225a.mp4

#### Fixes the following issue(s)

- Fixes #

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-07-31 22:03 UTC, TacoTheDank requested changes
Some comments:

2022-07-31 22:03 UTC, TacoTheDank commented on app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
> +                this.itemBinding = itemBinding;
Same here. Could one of these be renamed to prevent confusion?

2022-08-04 12:52 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
> +        final var context = requireContext();
I asked that on Element a while ago, and me + others from the team agreed that it is ok for `var` to be used, as makes code shorter and with less useless information to read. The only thing we don't want are PRs focusing just on replacing typed variables with `var`

2022-08-04 13:02 UTC, Stypox submitted a review, later dismissed
Good changes! I'll let @TacoTheDank complete the review and merge

2022-08-04 13:13 UTC, Isira-Seneviratne commented on app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchAdapter.java
> +        if (item.getBreadcrumbs().isEmpty()) {
The variable was annotated as NonNull, though.

2022-08-04 13:14 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchAdapter.java
> +        if (item.getBreadcrumbs().isEmpty()) {
You are right, ignore this

2022-08-11 19:34 UTC, TacoTheDank commented on app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
> +        final var context = requireContext();
That's fine with me 👍

2022-08-11 19:38 UTC, TacoTheDank commented
Sorry, I took a small break over the past week to relax after the past semester.

Could this be rebased to remove the dev merge commit?

2022-08-11 22:59 UTC, Isira-Seneviratne commented
> Sorry, I took a small break over the past week to relax after the past semester.
> 
> Could this be rebased to remove the dev merge commit?

Sure.

2022-08-12 21:21 UTC, TacoTheDank commented
@Stypox Are we doing a feature freeze until v0.24.0 is released, or can this be merged now?

2022-08-16 18:10 UTC, Stypox commented
No, we have not decided upon a freeze, you can proceed @TacoTheDank

2022-08-19 19:48 UTC, TacoTheDank approved these changes

2022-08-19 19:50 UTC, merged

2022-08-19 19:50 UTC, TacoTheDank commented
Thanks for this feature!