Use ListAdapter in NotificationModeConfigAdapter.
TeamNewPipe/NewPipe pull request #8841
Opened 2022-08-20 05:37 UTC by Isira-Seneviratne

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use `ListAdapter` in the notification mode adapter.

#### Fixes the following issue(s)

- Fixes #

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-11-22 10:27 UTC, Stypox requested changes
Looks almost good to me, thanks

2022-11-22 10:27 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/settings/notifications/NotificationModeConfigFragment.kt
>          val recyclerView: RecyclerView = view.findViewById(R.id.recycler_view)
Shouldn't you be using the `binding` here? `binding` is currently unused.

2022-12-28 20:44 UTC, Stypox requested changes
It does not work. Just open "Settings -> Notifications -> Channels" and tick a checkbox to see that everything disappears or the app crashes. Please test your PRs before submitting them (and before submitting any further change), otherwise it's just a waste of time to review things that don't work.

Another thing that you should do is make sure the CI succeeds. In this case it does not succeed because of a misformatted Kotlin file.

2022-12-29 00:52 UTC, Isira-Seneviratne commented
@Stypox Sorry about that, fixed.

2023-01-02 13:47 UTC, Stypox approved these changes
Code looks good and works. I pushed a small commit that further simplifies the handling of the disposables. Thank you!

2023-01-02 13:47 UTC, merged