Add Link to FAQ in the app
TeamNewPipe/NewPipe pull request #9164
Opened 2022-10-21 07:55 UTC by Yuuu2990

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
According to the instruction of the maintainer, add link to FAQ in the app.

#### Before/After Screenshots/Screen Record

- Before:
![before](https://user-images.githubusercontent.com/110877395/197141982-8004ded2-d692-4691-9fdb-e1e9cb90d144.png)
- After:
![after](https://user-images.githubusercontent.com/110877395/197142001-244f559c-eb20-4ef3-9127-b8d816ae5f06.png)

#### Fixes the following issue(s)

- Fixes #4447 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-10-22 13:45 UTC, opusforlife2 commented on app/src/main/res/values/strings.xml
> +    <string name="faq_description">View this website and you\'ll find answers to the questions we get asked the most about NewPipe.</string>
```suggestion
    <string name="faq_description">If you\'re facing any problems with using the app, make sure reading these is the first thing you do.</string>
```

2022-10-23 03:38 UTC, Yuuu2990 commented
@opusforlife2  I have committed your change. Hope everything is good. :-)

2022-10-23 15:50 UTC, AudricV requested changes
Thank you!

Please revert all the unneeded changes you or your IDE made, including the code style ones and the buttons size ones.

I think you tried to show everything without having to scroll, by reducing the buttons size. That's a really bad behavior, because:
- you decrease the accessibility of these buttons;
- devices have different aspect ratios, so you can't except to show everything on every device without having to scroll;
- what is applicable on portrait is not always applicable on landscape (and that's the case here).

2022-10-24 07:43 UTC, Yuuu2990 commented
@AudricV @opusforlife2 Hi, according to the advice form AudricV, I show everything with having to scroll. It's my problem to ignore the problems what AudricV. Anyway, hope it's fine now. :-)

2022-10-25 19:19 UTC, Stypox requested changes
Thanks, looks almost good to me ;-)

2022-10-25 19:19 UTC, Stypox commented on app/src/main/res/layout/fragment_about.xml
> +            android:id="@+id/textView2"
I don't think you need this
```suggestion
```

2022-10-25 19:19 UTC, Stypox commented on app/src/main/res/layout/fragment_about.xml
> +            android:id="@+id/newPipeTextView"
I don't think you need this
```suggestion
```

2022-10-25 19:19 UTC, Stypox commented on app/src/main/res/values/strings.xml
> +    <string name="faq">view on website</string>
Not really needed since it gets automatically uppercased, but for consistency
```suggestion
    <string name="faq">View on website</string>
```

2022-10-25 19:19 UTC, Stypox commented on app/src/main/res/values/strings.xml
> +    <string name="faq_description">If you\'re facing any problems with using the app, make sure reading these is the first thing you do.</string>
I think this is a better description. @opusforlife2 what do you think?
```suggestion
    <string name="faq_description">If you are having trouble using the app, be sure to check out these answers to common questions!</string>
```

2022-10-26 03:33 UTC, Yuuu2990 commented
@Stypox @opusforlife2 Hi, according to the advice from you, I have committed the changes. You can check it. :-)

2022-10-26 07:59 UTC, Stypox approved these changes
Looks good to me, thank you!
I tested the changes myself since the CI has trouble using the NewPipeExtractor library I think.

2022-10-26 07:59 UTC, merged

2022-10-26 08:58 UTC, Yuuu2990 commented
@Stypox @opusforlife2 Thank you very much for your suggestions while solving the issue. :-)