Add search type link
TeamNewPipe/NewPipe pull request #9181
Opened 2022-10-23 12:42 UTC by Sola0404

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Add SEARCH type case in the intent handler
- Add a method to generate an intent conveying the information of service id, URL, link type, and search string. This method is used in getIntentByLink when link type is SEARCH, distinguishing the conditions between using SEARCH link and open search.

#### Fixes the following issue(s)
Fixes #2313 

#### PR relies on
https://github.com/TeamNewPipe/NewPipeExtractor/pull/950

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-10-23 15:33 UTC, AudricV commented
Could you explain better what you added in this pull request? Also, it seems you did extractor changes for this, but you didn't use them in this PR. Please do so if that's needed.

2022-10-23 23:48 UTC, Sola0404 commented
Thank you for your response. I've updated the description. 
I changed extractor for this issue, but I don't know how to include these changes in this PR, cause they are from different repositories. Could you give me some advice? Thanks in advance!

2022-10-25 13:51 UTC, Stypox commented
You need to create a pull request in NewPipeExtractor, too. As you noticed, they are two different repositories, hence two different PRs ;-)

2022-10-25 14:48 UTC, ShareASmile commented
> @Sola0404 You need to create a pull request in NewPipeExtractor, too.

@Stypox it's already been opened on extractor https://github.com/TeamNewPipe/NewPipeExtractor/pull/950

AudricV wrote:
> it seems you did extractor changes for this, but you didn't use them in this PR. Please do so if that's needed.

Stypox @Sola0404 is asking how to use extractor commits in this PR

2022-10-27 12:53 UTC, Stypox requested changes
Are urls copied to the search field in NewPipe handled as opened URLs?

2022-10-27 12:53 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
> +                    linkType, service.getIdByUrl(url));
Intead of obtaining the ID this way, as said in https://github.com/TeamNewPipe/NewPipeExtractor/pull/950#discussion_r1006825163, I think you should use `service.getSearchLHFactory().getId(url)`.

2024-03-28 15:27 UTC, Stypox commented
I'm closing this for now, both because of inactivity, and because we're going to start the rewrite soon and this would get conflicts despite its simplicity. I'm leaving https://github.com/TeamNewPipe/NewPipeExtractor/pull/950#issuecomment-2025494747 open though, so once that is done and the rewrite is in a good shape this can be reopened. Thank you!

2024-03-28 15:27 UTC, closed without merging