Channel tabs
TeamNewPipe/NewPipe pull request #9182
Opened 2022-10-23 23:08 UTC by Theta-Dev

Because YouTube is planning to update their channel page layout (as announced [here](https://www.youtube.com/watch?v=czIyqEC4V-s)) and divide videos into 3 tabs (regular videos, shorts, livestreams), we need to add this layout to the NewPipe app to be able to access all channel content.

#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- add a tabbed channel layout with tabs for videos, shorts, livestreams, playlists, featured channels and channel info
- add a settings option to hide certain channel tabs
- add a debug only option to set a YouTube visitor data cookie (allows for testing the new layout)

#### Before/After Screenshots/Screen Record

https://libreddit.kavin.rocks/r/NewPipe/comments/ybvl5t/update_on_the_channel_tabs_feature_debug_apk/

#### Fixes the following issue(s)

- Fixes #2414

#### Relies on the following changes

- TeamNewPipe/NewPipeExtractor#951

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9847738/app-debug.zip)

To test the new tab layout, go to Settings > Debug > YouTube visitor data and set it to this value:
`CgtOa256ckVkcG5YVSi7-c6aBg%3D%3D`

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-10-24 02:00 UTC, opusforlife2 commented
Dun dun DUUUUUUUN. It's happening. It's finally happening. ಥ‿ಥ

2022-10-24 11:21 UTC, opusforlife2 commented
Opening non-video items in channel tabs and then going back causes the entire channel info to be loaded again. Can it not be cached? Or opened as a fragment or something like video details pages are?

---

Crash crash crash! If you open any item from a non-video channel tab and then open a video, going full screen causes this crash:

<details>

```
FATAL EXCEPTION: main
Process: org.schabi.newpipe.debug.channeltabs, PID: 17217
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout org.schabi.newpipe.databinding.FragmentChannelBinding.tabLayout' on a null object reference
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onSaveInstanceState(ChannelFragment.java:134)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0$androidx-fragment-app-FragmentManager(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at android.app.Activity.performSaveInstanceState(Activity.java:2203)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1520)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5830)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5229)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5784)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5703)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

</details>

2022-10-24 19:23 UTC, bizz91 commented
Can we get the ability to disable shorts from all newpipe feeds please?

2022-10-25 08:47 UTC, Theta-Dev commented
@opusforlife2 I published a new debug build (v3) that should fix your issues

2022-10-25 12:33 UTC, opusforlife2 commented
Confirmed. Thanks!

2022-10-29 05:56 UTC, tvnmguy commented
Some design suggestion for new channel tabs!


![IMG_20221029_111450.jpg](https://user-images.githubusercontent.com/116799295/198816201-019c2a9f-1797-456f-8052-57f6114e8679.jpg)


![IMG_20221025_101021.jpg](https://user-images.githubusercontent.com/116799295/198816212-476090c6-9002-40d4-b1a6-6631bda44fc6.jpg)


![IMG_20221025_101613.jpg](https://user-images.githubusercontent.com/116799295/198816222-e6d45d4f-9a15-48db-bd5c-84a3b7c2dd3a.jpg)


![IMG_20221025_100719.jpg](https://user-images.githubusercontent.com/116799295/198816230-856ae02e-a34b-45c3-a31c-c14b1d3b8379.jpg)


![IMG_20221025_102008.jpg](https://user-images.githubusercontent.com/116799295/198816240-07e0597a-b27c-4bdd-b953-bdf8c925177c.jpg)


![session-2022-10-25-110503.jpg](https://user-images.githubusercontent.com/116799295/198816248-fed409ab-792a-4bdf-9ced-3d980f1ade9b.jpg)


![IMG_20221029_105634.jpg](https://user-images.githubusercontent.com/116799295/198816264-679d796c-a3f6-439e-b1ee-fd7f0129dabe.jpg)



Some channels doesn't feature Home video, then the channel tab look like this👇


![IMG_20221029_111227.jpg](https://user-images.githubusercontent.com/116799295/198816323-6e955f67-e613-4498-b62f-362e89074470.jpg)

2022-10-29 08:02 UTC, tvnmguy commented
Is possible to implement search something in a channel?

If possible... My design is here👇



![img_2022_10_29_13_23_48.jpg](https://user-images.githubusercontent.com/116799295/198820737-731023d9-99ea-4524-b28c-89f9e5546da4.jpg)


![IMG_20221029_131703.jpg](https://user-images.githubusercontent.com/116799295/198820814-a7511c3b-88e8-4822-8f29-f01d29280ec2.jpg)


![img_2022_10_29_13_23_48.jpg](https://user-images.githubusercontent.com/116799295/198820831-3ade06ae-22f6-4e89-8761-b161da4b8fe5.jpg)


![img_2022_10_29_13_08_48.jpg](https://user-images.githubusercontent.com/116799295/198820834-97014bc9-3ebb-4523-b082-4512e4ebc56f.jpg)


![img_2022_10_29_13_05_50.jpg](https://user-images.githubusercontent.com/116799295/198820842-1850763c-06fc-4f0e-9b2a-9f9776319896.jpg)


![img_2022_10_29_13_01_56.jpg](https://user-images.githubusercontent.com/116799295/198820855-5d4dc142-bb0f-4dfd-bfa1-5041c0ac1a0a.jpg)

2022-10-29 08:21 UTC, Theta-Dev commented
@SameenAhnaf Did you open this playlist from the channel playlists tab? I tried it and could not reproduce this issue.

This PR does not touch any playlist extraction code, so that issue may also occur when opening a playlist manually.

A quick fix would be to clear the cache and reopen the playlist.

2022-10-29 20:04 UTC, Theta-Dev commented
It is not possible to merge all 3 tabs into one feed because YouTube does not show the upload date of shorts.

We could omit the shorts and merge the video and livestream tab into the feed.

An alternative would be to fetch both the channel tab and the RSS feed. That would be faster than fetching 2 tabs and we would still get all the shorts and livestreams

2022-10-30 16:32 UTC, opusforlife2 commented
I haven't set the visitor data cookie, yet I'm suddenly seeing the Shorts and Live tabs. I wasn't seeing them a couple of days ago when I tested debug3. A/B testing is the culprit, I assume?

2022-11-02 10:30 UTC, WorkHard4470 commented
Image or thumbnail doesn't load.

## Exception
* __User Action:__ load image
* __Request:__ https://i.ytimg.com/vi/XgvuIGwYIpk/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgUihEMA8=&rs=AOn4CLCzqLb2G-9A61HkSVzBNIITMhqUvg
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 404
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

```
</details>
<hr>

2022-11-06 00:58 UTC, Theta-Dev commented
> Channel tabs seem to be inaccessible if added as a content on main page. Only, normal videos are shown.

That is intentional. The main page already used a tabbed layout, so we cant have another tab bar inside.

2022-11-06 01:17 UTC, tsiflimagas commented
One thing I noticed is that when being on any tab other than the "VIDEOS" one, if you rotate the screen, you're moved back to it (the videos tab).

2022-11-06 01:25 UTC, WorkHard4470 commented
Please @Theta-Dev resolve the checks and resolve branch conflicts.

2022-11-06 12:23 UTC, c0h2r commented
Got this when reloading the feed some time after watching this particular video. Not sure if it's related to the pr or is by any means important, tho. Otherwise, no problems encountered so far; great job! And thanks for removing shorts and streams from the "what's new" tab, they were kinda annoying 🙃

## Exception
* __User Action:__ play stream
* __Request:__ Loading failed for [Сразу несколько новых проектов. Большой анонс с veloline и stark]: https://www.youtube.com/watch?v=twjbDeKip2s
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.player.mediasource.FailedMediaSource$MediaSourceResolutionException: Unable to resolve source from stream info. URL: https://www.youtube.com/watch?v=twjbDeKip2s, audio count: 0, video count: 12, 2
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$3$org-schabi-newpipe-player-playback-MediaSourceManager(MediaSourceManager.java:432)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

2022-11-07 08:48 UTC, tvnmguy commented
Also some videos are Missing thumbnail in what's new feed as well 


Yes

2022-11-07 08:48 UTC, tvnmguy commented
> Also some videos are Missing thumbnail in what's new feed as well 
> <img alt="Screenshot_2022-11-07-11-40-53-06_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200238220-0fd92a97-ccc7-4870-9786-aae37a434741.png" height=600 />
> 
> 
> 

Yes, me too

2022-11-23 03:31 UTC, wCTcTU4P commented
Good experience with debug 4 on my end. Also, perhaps I'm missing something, but shouldn't the "what's new" section have videos / shorts / live all together? That is of course how it was before the youtube channel tabs update.

To be clear, the NP channel tabs update here is great - huge improvement.

2022-11-23 03:57 UTC, Feuerswut commented
> Good experience with debug 4 on my end. Also, perhaps I'm missing something, but shouldn't the "what's new" section have videos / shorts / live all together? That is of course how it was before the youtube channel tabs update.
> 
> To be clear, the NP channel tabs update here is great - huge improvement. 

no, shorts are cancer and there will be an option to hide them. or another section. live videos and announcements are on top, announcements only if option show future videos is set.

2022-11-23 18:21 UTC, wCTcTU4P commented
> > Good experience with debug 4 on my end. Also, perhaps I'm missing something, but shouldn't the "what's new" section have videos / shorts / live all together? That is of course how it was before the youtube channel tabs update.
> > To be clear, the NP channel tabs update here is great - huge improvement.
> 
> no, shorts are cancer and there will be an option to hide them. or another section. live videos and announcements are on top, announcements only if option show future videos is set.

Personally, I agree and don't care for shorts whatsoever. On the development end, I would think it would be an option of what combinations of the 3 subsets (shorts, vids, live, unless I am missing something else) the user wants to have in their "What's New" feed, with the default being "All". 

Also, just to clarify on lives - I have seen them at the top, but when they are posted afterwards, they do not seem to be appearing in the What's New feed. That specifically was the issue I identified (for my personal use). Previously, post-live video postings were in the feed, and now they are not, even in debug v4 from testing yesterday.


In addition, I just remembered one further piece of feedback - I found that the playlists tab on a test channel only had the 1st playlist category that I see here: https://www.youtube.com/c/3blue1brown/playlists. 

Specifically 3Blue1Brown has several playlist categories (meta-playlists?), "Created Playlists", "Series", "Projects on other channels". What I saw in debug v4 corresponded only to the first one listed, "Created Playlists", I believe. 

Another example - PBS spacetime has a special category of playlists as well: https://www.youtube.com/@pbsspacetime/playlists. It seems that can be user defined, but basically it seems newpipe would want to have the superset of "Created Playlists" as well as any other user-defined playlist categories (or meta-playlists, if you will). 

If I need to clarify or if I am just remembering wrong or something, please let me know, but I believe this is what I encountered in my brief test yesterday.

2022-11-23 18:56 UTC, Feuerswut commented
have you set the cookie to receive the 3 tab layout data?

2022-11-26 21:23 UTC, wCTcTU4P commented
> have you set the cookie to receive the 3 tab layout data?
> 
> i get all playlists and have not set the cookie.
> 
> <img alt="Screenshot_20221123-195822.png" height="600" src="https://user-images.githubusercontent.com/80217805/203626670-f5c32044-d521-4a30-b14d-cb3d35af733c.png">
> 
> <img alt="Screenshot_20221123-195816.png" height="600" src="https://user-images.githubusercontent.com/80217805/203626693-358c36b4-a443-49e6-857b-b33552e09c4e.png">

Sorry for the slow response. Regarding the cookie, I'm not sure what you're referring to - I downloaded debug4 and didn't alter any settings (haven't seen one regarding cookies, so idk exactly where it is). 

So I see that PBS Spacetime actually shows correctly in NewPipe. However, 3Blue1Brown does not have some other playlists lists as before. Have you tried that one on your end? Specifically upon review, it seems "Created playlists" and "Projects on other channels" categories are in NewPipe. So it is just "Series" playlists that aren't there. Perhaps that is a... special playlist category of some type that is being missed by NewPipe?

Also, is there any word on post-live video postings (VODs, I guess is the term?) being in the "What's New?" section? Not sure if that relates to the cookie you mentioned.

2022-11-28 16:10 UTC, Stypox requested changes
First of all, thank you very much for this PR! Overall code structure looks good, but there are still some things to refine. :-D

----

The "Info" tab does not look so good in my opinion.
- The description should have more space around it, for example: copy margin values from `fragment_description.xml`.
- The title "Description" at the top is not needed in my opinion.
- You should be able to add more metadata values in this tab probably (e.g. join date, total number of views, location, @ handle, and links), though that's not needed as of now.
- "Info" should be renamed to "About", which is YouTube's name for that tab (also rename related files).
- Maybe we might want to merge the "Channels" tab with the "About" tab. Related channels are not really a _content_ of the channel, but rather a metadata item, and as such they are used less frequently and in my opinion would fit better in its section in the "About" tab. This would also reduce the amount of tabs by 1, making scrolling simpler.
<img src="https://user-images.githubusercontent.com/36421898/204318617-0e9027d6-f7b2-49ef-a546-d5861361c056.png" width="200px"/>

----

A few other notes:
- You should set `implementation 'com.github.Theta-Dev:NewPipeExtractor:f7e3b713b57dfc9a47a2760574fc752bb6dab425'` in `app/build.gradle`, so that the code builds, the CI runs and you don't need to keep providing APKs
- ~~The back button on the top-left of the screen should behave just like the phone back button. Try to tap on a channel inside of another channel's "Channels" tab, and then go back, to understand what I mean.~~
- The channel-name title in the toolbar isn't restored when returning to the channel fragment after having opened e.g. a playlist from the "Playlists" tab and then having gone back.
- Loading more shorts does not work: the loading indicator disappears after a few milliseconds without adding newly loaded shorts, even though the channel has more shorts. You can use [this channel](https://www.youtube.com/@PiperRockelle) to test. This might happen with related channels, too, though I couldn't find a channel with so many related channels. Loading more playlists works, though, as you can see on [this channel](https://www.youtube.com/channel/UCyeVfsThIHM_mEZq7YXIQSQ).
- Avoid translating strings into languages you know inside PRs: you will be able to do so from Weblate once this PR will be merged. As you can see there is a conflict on `values-de/strings.xml` now ;-)

2022-11-28 16:16 UTC, opusforlife2 commented
> The back button on the top-left of the screen should behave just like the phone back button. 

@Stypox There was a discussion around this, and I think it was Mauricio who mentioned that the Back arrow works differently from the Back button. The button goes back through the entire chain of opened pages, but the arrow goes "up one level".

If that behaviour is changed, it would become inconsistent with the Back arrow's behaviour in the rest of the app.

2022-11-28 16:20 UTC, Stypox commented
> If that behaviour is changed, it would become inconsistent with the Back arrow's behaviour in the rest of the app.

Uhm, which "rest of the app" are you referring to? Also, can you mention any guideline explaining that this is the standard behavior on Android? I don't think it is...

2022-11-28 16:32 UTC, opusforlife2 commented
I don't know about guidelines, all I know is what the button is supposed to do based on what I remember from Mauricio's comments. Here's an example:
- Open a channel
- Open a video from that channel.
- Open a related video's channel.
- Now tap either Back button or Back arrow.

Button will take you from the 2nd channel to the 1st. Arrow will close the channel view entirely.

2022-11-28 16:35 UTC, Stypox commented
Ok then, let's ignore this in this PR and in case discuss it separately

2022-11-29 12:11 UTC, Theta-Dev commented
The missing shorts continuation is an extractor issue. YouTube appearently returns an empty response when fetching shorts continuations without visitor data.

2022-11-30 07:04 UTC, Theta-Dev commented
Is there already a PR for NewPipe to use the new html comment format? I have merged the latest dev branch into my extractor fork and found NewPipe not functional. My quick fix to get it to build resulted in html code in comments.

2022-12-05 20:34 UTC, testertv commented
Also I noticed that this issue happens if you put stream in a playlist before/during/after starting the stream. Then it doesn't visible in the "Videos" section of YouTube, only in playlists and consequently not in the App. Similar issue with shorts.

2023-02-09 09:36 UTC, immanuelfodor commented
A humble request to pay more attention to the tabs feature please to get it merged, it's a huge pain that live videos are not visible anymore in NewPipe 😞

2023-03-05 09:29 UTC, anton-isidore commented
When I exported backup from my NewPipe app and then imported it into apk debug 4 from this issue I have got crash


## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: A migration from 6 to 5 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)
	at androidx.room.RoomOpenHelper.onDowngrade(RoomOpenHelper.java:129)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.java:194)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:526)
	at androidx.room.util.DBUtil.query(DBUtil.java:86)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$9.call(FeedDAO_Impl.java:496)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$9.call(FeedDAO_Impl.java:493)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

2023-03-05 10:04 UTC, anton-isidore commented
Also is there a plan to incorporate live videos into the What's New feed?

This is my most missing think. I have to manually check if there was a lifestreem for every channel separately.

2023-03-06 23:51 UTC, n-buna404 commented
> When I exported backup from my NewPipe app and then imported it into apk debug 4 from this issue I have got crash

I think this was explained before that the backup was only forward-compatible but not backward-compatible. This PR and generated was based on 0.24.0 so if you import any backup from newer newpipe such as 0.25.0  it would fail.

2023-03-07 00:13 UTC, wCTcTU4P commented
> 

I mentioned this in November as well. In my opinion, the What's New feed should be updated to match the legacy style before youtube split videos into tabs. Having to search for Live VOD's in every individual channel is very cumbersome and undesirable for users.

2023-03-17 07:51 UTC, welkinpc-91 commented
> Also is there a plan to incorporate live videos into the What's New feed?
> 
> This is my most missing think. I have to manually check if there was a lifestreem for every channel separately.

If you can handle incomplete metadata, switching to RSS feed (fetch from dedicated feeds in content menu settings) will do that. (I'm on 0.25.0 but it should work in this 0.24.0 test version...I think?)

It gets shorts and livestreams but without time lenghts for me.

2023-03-17 17:44 UTC, nicoursi commented
> > Also is there a plan to incorporate live videos into the What's New feed?
> > This is my most missing think. I have to manually check if there was a lifestreem for every channel separately.
> 
> If you can handle incomplete metadata, switching to RSS feed (fetch from dedicated feeds in content menu settings) will do that. (I'm on 0.25.0 but it should work in this 0.24.0 test version...I think?)
> 
> It gets shorts and livestreams but without time lenghts for me.

Wow, thank you for this trick! Until they fix it this is a good work around.

2023-04-05 18:26 UTC, AudricV commented
b108e2801d8bb0040bf2b7e7372b765d7a48e70d is useless, as [`isBlank` already checks if strings are null](https://github.com/TeamNewPipe/NewPipeExtractor/blob/8495ad619ebad02a0c483b3931ed5f06d42f0b30/extractor/src/main/java/org/schabi/newpipe/extractor/utils/Utils.java#L309-L311).

Sonar raised the nullability issue as it is not able to understand custom nullability checks.

2023-04-05 19:40 UTC, Theta-Dev commented
okay, I'll revert that.

2023-04-12 22:06 UTC, Stypox commented
I pushed a commit that moves the channel header inside the now-collapsible app bar. This meant that a lot of code was moved back from `ChannelVideosFragment` to `ChannelFragment`. I also rearranged the header layout using a `ConstraintLayout`, which fixed some sizing issues (e.g. the annoying border around the channel banner). Now when there is no banner in a channel, the placeholder image is not shown at all, to save precious space (just try any SoundCloud channel to verify this).

2023-04-13 20:29 UTC, Theta-Dev commented
I like your new channel header design, @Stypox.
Just fixed a tiny issue with the notification menu option disappearing on tab changes.

In my opinion the new header becomes too tall in landscape mode though. Here are some screenshots:

The styles are applied to the `fragment_channel.yml > @+id/channel_banner_image` image view

### Current header:
![old_banner](https://user-images.githubusercontent.com/19636565/231874472-b92190a9-6ec0-4286-b825-69e6d0bd29b3.png)

### New header:
![tall_banner](https://user-images.githubusercontent.com/19636565/231874210-8f802378-f104-4bf4-b507-bc1d7131bb97.png)

### Cropped
`maxHeight="70dp" scaleType="centerCrop"`

![short_banner](https://user-images.githubusercontent.com/19636565/231875072-cb86cfc0-d43a-48bb-abfc-8ea971e12f10.png)

### Scaled (transparent)
`maxHeight="70dp" scaleType="fitCenter"`

![banner_fit_transp](https://user-images.githubusercontent.com/19636565/231875354-28e017bb-fdbe-4238-8b2c-313577a39646.png)

### Scaled (black, like the old design)
`maxHeight="70dp" scaleType="fitCenter" background="@color/black"`

![banner_fit_black](https://user-images.githubusercontent.com/19636565/231875423-e343e2ca-b292-4e89-a5b8-79295f8d7113.png)


I would prefer the cropped version. What do you think?

2023-04-13 21:02 UTC, Feuerswut commented
![Screenshot_20230413-225526.png](https://user-images.githubusercontent.com/80217805/231881026-289ff5bb-d37e-4a29-95b7-f12e33c61de8.png)

I would completely hide the channel banner like this. May also move the channel icon between the back arrow and upper channel name. 

There really is not enough space to even scroll. (Its less significant on a 16:9 but still too little workspace.

P.S.: The latest 2 builds had black flickering while playback (for some possibly unrelated reason)

Great work so far I really like the vertical view.
![Screenshot_20230413-230008~2.png](https://user-images.githubusercontent.com/80217805/231881934-0485380c-3e02-4799-889e-afc502f740e5.png)

Though maybe drop the first channel name like this in this view mode.

2023-04-13 21:15 UTC, Feuerswut commented
like this?
(wanky illustration.png)
![image12.png](https://user-images.githubusercontent.com/80217805/231884557-c708902b-b0d4-499b-bc8c-29af5df3fcb5.png)

2023-04-14 08:57 UTC, Stypox commented
I pushed a rather big commit:
- Now `ChannelInfo` is not a `ListInfo` anymore, but just an `Info`. So there is no privileged tab anymore stored in `relatedItems`, but rather each tab is in its own `ListLinkHandler` returned by `getTabs()`. On the extractor side, I still made it so that the `ListLinkHandler`s contain the data that has already been fetched, in order to avoid multiple network requests.
- Now the non-fast feed loads all "playable" channel tabs to get the new streams of a channel. By "playable" I mean a tab that contains videos, tracks, shorts and livestreams. So now all of this content will be present in the feed.
- Now subscribing to a channel does not automatically add all of its videos to the feed, but this will happen on the next feed reload. Previously this was being done because when subscribing all of a channel's streams would certainly already have been loaded, but now the streams come from many tabs, some of which may have not been loaded, so it's just simpler to load everything on the next feed reload.
- YouTube shorts are now fetched when reloading the feed, but since they have no upload date (there is no way to extract it), they are discarded by the feed loading logic. What should we do about this? Should we keep all items with no upload date into the feed, maybe putting them at the end of the feed?
- When channels are shown on the main page, at the moment all of their tabs are shown. As pointed out before this is a bad idea, because you would get two nested tab layouts. But a simple solution exists: showing only the first channel tab if `useAsFrontPage` is true. What do you think?

> In my opinion the new header becomes too tall in landscape mode though.

Right. I like the "Scaled (black, like the old design)" option.

> Could the cover image go under the whole header as a background and dimmed under the white texts with some shadow to keep them readable even on white cover image? It could look pretty sleek. 

I know, but with the current way the toolbar is dealt with, I don't think it would be simple to do so, unfortunately.

2023-04-14 11:04 UTC, yoshimo commented
When you open the YT Page of an Individual Short and then go to the description:
![grafik](https://user-images.githubusercontent.com/17909/232026526-29f88d37-2656-40b5-99b1-1166769d2ec6.png)
![grafik](https://user-images.githubusercontent.com/17909/232026870-d8dfc174-6cc6-494a-b9f9-d07efe9a4c4b.png)
leads to a page that has the element
```<meta itemprop="uploadDate" content="2022-09-19">```
maybe you need to grab data for individual feed shorts separately?

2023-04-14 11:53 UTC, Stypox commented
> maybe you need to grab data for individual feed shorts separately?

It's not a good idea to load each short individually, since it would mean making hundreds of requests for each channel each time the feed is reloaded.

2023-04-14 13:52 UTC, yoshimo commented
So there is no way to store& cache Date per Short Video and only request unknown data? then yes , it should be left without date.

2023-04-14 15:51 UTC, Theta-Dev commented
I do have an idea how to fetch a channel's latest videos, shorts and streams with a single request: using the Smart TV client.

YouTube's TV client shows the latest channel content on a single page.

The continuation system is weird, as it provides an infinite carousel of videos, even if the channel only has 1 video. So using the TV client for fetching the video tab is a bad idea.

But we could use the TV client as an alternative FeedExtractor to provide a list of the latest ~10 streams.

And unlike the RSS feed the TV client provides all the required metadata: approximate upload date, video length and the date of a future livestream.

I am currently writing a prototype to test it.

2023-04-14 16:42 UTC, Stypox commented
Here is a conversation happened on IRC that probably would solve the problem (btw, did you manage to join?)

> Note: we recently discovered that YouTube system playlists exist for regular videos of channels, for livestreams, and shorts as chronological ones (the shorts one was already known) and popular ones.
> They correspond basically to the results of the sort filters available on the channels streams tab on YouTube's interface

> So, basically shortcuts for the lazy/incurious?

> Same procedure as the one described in the 0.24.1 changelog, except that you need to change the prefix `UU` (all user uploads) to:
- `UULF` for regular videos only,
- `UULV` for livestreams only,
- `UUSH` for shorts only,
- `UULP` for popular regular videos,
- `UUPS` for popular shorts,
- `UUPV` for popular livestreams
- `UUMF`: members only regular videos
- `UUMV`: members only livestreams
- `UUMS` is probably for members-only shorts, we need to found a channel making shorts restricted to channel members

2023-04-14 17:36 UTC, Theta-Dev commented
That's a good idea for extracting shorts with all the required metadata. For all the other types we can keep using the channel endpoint.

2023-04-15 19:58 UTC, nicoursi commented
There seem to be a problem with peertube. Three channels show the same videos all coming from different channels: 
https://peertube.it/video-channels/alfa_omega_channel
https://peertube.it/video-channels/my_q_chanel
https://peertube.it/video-channels/veritas_chanel

2023-04-16 09:30 UTC, Theta-Dev commented
Yes, I have already fixed that but but pushed it

2023-04-16 14:08 UTC, Theta-Dev commented
Okay, I fixed some issues with the latest version

- added back playlist controls to channel tabs
- fix crashes when rotating, locking/unlocking or minimizing the app on a channel page
- fetch YouTube shorts using YouTube's internal playlist

Note: if you used an older version of this dev build, make sure that the "Videos" and "Track" channel tab types are enabled in the Content > Channel tabs setting. They got added afterwards and default to false if the option was changed before.

2023-04-16 14:23 UTC, Feuerswut commented
crash after loading feed from subscribed channels using fast feed loading method

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept, parameter error
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(Unknown Source:7)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt:96)
	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

2023-04-16 15:39 UTC, nicoursi commented
It still crashes even after eb448a0

2023-04-17 20:57 UTC, Theta-Dev commented
Since I cannot reproduce your crash, I could not verify if I fixed it.
Just try out the latest debug build [`6bc16d8`](https://github.com/TeamNewPipe/NewPipe/pull/9182/commits/6bc16d8b748c85677b1a5b10057a0478ddba8cff) if you had this crash.

2023-04-17 22:17 UTC, peat80 commented
I also had this crashes with eb448a0 and 6bc16d8 fixes it for me. 😎👍

2023-04-18 05:11 UTC, Feuerswut commented
> I also had this crashes with eb448a0 and 6bc16d8 fixes it for me. 😎👍

me as well

2023-04-21 21:51 UTC, Feuerswut commented
![Screenshot_20230421-234815](https://user-images.githubusercontent.com/80217805/233739982-f727062d-d5ce-4e05-b281-9816a1ba7a92.png)
Works so far, though the channel avatar should be this (1) instead of this (2) url.

(1) https://yt3.googleusercontent.com/ytc/AGIKgqNiyd4a1wz6CkAa6VHoUk_yyx-akvQuuGUSfWkcuE4

(2) https://yt3.googleusercontent.com/ytc/AGIKgqNiyd4a1wz6CkAa6VHoUk_yyx-akvQuuGUSfWkcuE4=s48-c-k-c0x00ffffff-no-rj

2023-04-24 19:45 UTC, yoshimo commented
You can select  videos, shorts, tracks and live in the content part of the settings menu. I'd love  to see an optional tab on the channels menu that combines all of them into a single list so you have all content of a channel on one infinite page and can scroll down.

2023-04-25 18:56 UTC, Stypox reviewed
Code looks good to me. I pushed some other small commits. I renamed settings keys containing "live" to now contain "livestream" for consistency. This will mean that for users upgrading from test APKs the setting will be disabled.

A few notes:
- At the moment the tabs ViewPager pre-fetches 1 tab to the left (and to the right) of the currently selected tab, which ends up making useless network requests if the user just wants to view the first tab. However, [there is no way](https://stackoverflow.com/questions/23959144/how-can-i-disable-the-preloading-in-a-viewpager) to tell the ViewPager to preload less than 1 tab, so we need to keep it this way.
- > When channels are shown on the main page, at the moment all of their tabs are shown. As pointed out before this is a bad idea, because you would get two nested tab layouts. But a simple solution exists: showing only the first channel tab if useAsFrontPage is true. What do you think?

  What do we want to do about this then?
- Previously the subscription import service also stored the videos of the channels being imported in the feed. In order to make the import process smoother,  this won't happen anymore, and instead the user will need to reload the feed manually. Note that importing subscriptions is a one-off thing, so I doubt this change would be in any way annoying, and also it didn't really work "as expected" even before since it never used the fast-feed.

2023-04-30 16:05 UTC, nicoursi commented
> now the recording of past livestream doesn't even show in feed page (used to be able to see them)

Are you sure it is activated from the settings? Check Settings→contents→fetch channel tabs

2023-05-24 20:18 UTC, Eiion commented
@Stypox made a request for changes blocking the merking of this pull request. What are these requested changes? Either I can't find them or they aren't here to see.

2023-05-26 13:17 UTC, mselmanyildirim commented
Hi,
Thanks for all your efforts, I really like NewPipe.
Channel tabs are very important, since the default tab in the official release lacks most video in the other tabs (such as live or shorts, etc.)
**Is there any planned date for merging this branch into the official release?** I've been using this branch for a while to be able to get all videos in the channel page.
Thanks..

2023-06-01 06:17 UTC, shuvashish76 commented
Steps to reproduce :
 1. Cycle through few tabs quickly
 2. Open sidebar
 3. Click on Settings

_Also noticed that switching tabs & opening/closing settings page is very slow._
 
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux motorola/corfur_g/corfur:12/S2RUB32.51-15-9/608d8b-b6a90:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2390988 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: android.os.TransactionTooLargeException: data parcel size 2390988 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
	... 9 more

```
</details>
<hr>

2023-08-02 20:58 UTC, Stypox commented
I pushed a commit that makes use of https://github.com/TeamNewPipe/NewPipeExtractor/pull/1082 intead of https://github.com/TeamNewPipe/NewPipeExtractor/pull/951. New debug APK built by me: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/12244479/app-debug.zip).

2023-08-02 21:20 UTC, Feuerswut commented
> I pushed a commit that makes use of https://github.com/TeamNewPipe/NewPipeExtractor/pull/1082 intead of https://github.com/TeamNewPipe/NewPipeExtractor/pull/951. New debug APK built by me: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/12244479/app-debug.zip).

Is this using the 0.25.2 release version as a base?

2023-08-02 21:44 UTC, Stypox commented
No, as you can see there are still conflicts that need to be solved

2023-08-11 05:16 UTC, gab12 commented
> I pushed a commit that makes use of [TeamNewPipe/NewPipeExtractor#1082](https://github.com/TeamNewPipe/NewPipeExtractor/pull/1082) intead of [TeamNewPipe/NewPipeExtractor#951](https://github.com/TeamNewPipe/NewPipeExtractor/pull/951). New debug APK built by me: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/12244479/app-debug.zip).

Oh, thank you so much!
I've been using the Theta-Dev apk for over a year now and I love it. I can't live without it.
I've given up on the official version (24, 24.1, 25,25.1,25.2) as it still doesn't integrate this wonderful feature.
So I'm glad to see that the PR is progressing and that I can finally update the app. Many thanks again

2023-08-11 11:24 UTC, ShareASmile commented
Sponsorblock version of above PR is here
https://github.com/Justus6568/NewPipe/releases/tag/v0.25.2

2023-08-22 11:45 UTC, TobiGr reviewed
Looks good to me, but the `SubscriptionManagerTest` is failing.

2023-08-24 18:28 UTC, AudricV commented on app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
>                  updateNotifyButton(null);
The channel header with its subscribe button is now shown for all tabs, so it should be not an issue anymore.

2023-08-29 17:35 UTC, TobiGr commented
Rebased and added a new commit: [Deduplicate code to initialize ClickListeners on playlist controls (`ecff198`)](https://github.com/TeamNewPipe/NewPipe/pull/9182/commits/ecff198365946ac4d6d112010cea9fa0a4127e46)

Add the separate utility class PlayButtonHelper to handle the initialization of the listeners.

Additionally, the behaviour of the "Hold to enqueue" hint is changed. The hint was only shown when clicking on the background or popup button in the LocalPlaylistFragment despite the corresponding setting saying 'Show tip when pressing the background or the popup button in video "Details:"'. The hint is now shown when making a normal click on the background, play all, and popup buttons in all playlist controls as well as the DetailFragment. The hint displayed until the user enqueued streams three times using a longpress click.

This commit also refactors the way how the app determines whether it is started for the first time. The previous version was not clean and recent in this PR caused it to fail. The regression was detected while creating a new SettingMigration to change the value of show_hold_to_append_key from boolean to int.

2023-08-29 20:30 UTC, VA1DER commented
If and when there is time, a new binary build of this PR would be appreciated.

2023-08-30 19:57 UTC, TobiGr commented
Did you upgrade from a previous channel tabs version or did you do a clean install of the channel tabs APK? It's caused by my last commit.

2023-08-30 20:01 UTC, nicoursi commented
> Did you upgrade from a previous channel tabs version or did you do a clean install of the channel tabs APK? It's caused by my last commit.

Clean install but then i imported settings and database from previous channel-tab apk

2023-08-30 20:09 UTC, Feuerswut commented
It is not caused while the database is empty/default.

2023-08-30 20:10 UTC, Feuerswut commented
> > Did you upgrade from a previous channel tabs version or did you do a clean install of the channel tabs APK? It's caused by my last commit.
> 
> Clean install but then i imported settings and database from previous channel-tab apk

That is not 'clean' in the way Tobi means. I also have this crash if I import my settings.

Ill poke around for a bit...

2023-08-30 20:19 UTC, nicoursi commented
After more testing  I can say that it crashes only if I import the settings, but it does not crash if I import the database only.

2023-08-30 20:33 UTC, Feuerswut commented
Settigs (old): (causes crash)
> ```
�� sr java.util.HashMap���`� F 
loadFactorI 	thresholdxp?@     �w      {t &scale_to_square_image_in_notificationssr java.lang.Boolean� r�՜�� Z valuexpt resume_on_audio_focus_gainq ~ t screen_brightness_timestamp_keysr java.lang.Long;��̏#� J valuexr java.lang.Number������  xp  up���t tablet_modet offt popup_remember_size_pos_keyq ~ t show_original_time_ago_keysq ~  t enable_playback_state_listsq ~ t limit_mobile_data_usaget 360pt channel_tabssr java.util.HashSet�D�����4  xpw   ?@     t show_channel_tabs_livet show_channel_tabs_albumst show_channel_tabs_videost show_channel_tabs_channelst show_channel_tabs_infot show_channel_tabs_aboutt show_channel_tabs_trackst show_channel_tabs_playlistsxt streams_notifications_intervalt 900t app_language_keyt det "use_exoplayer_decoder_fallback_keyq ~ t popup_saved_widthsr java.lang.Float��ɢ�<�� F valuexq ~ D4@ t default_popup_resolutiont 1080p60t show_higher_resolutionsq ~ t last_resize_modesr java.lang.Integer⠤���8 I valuexq ~     t 
show_commentsq ~ t use_external_video_playerq ~ t notification_slot_compact_1_keysq ~ )   t show_thumbnail_keyq ~ t feed_show_played_itemsq ~ t notification_slot_4_keysq ~ )   t youtube_visitor_datat kekt "enable_lock_screen_video_thumbnailq ~ t show_crash_the_player_keyq ~ t download_path_audiot Mcontent://com.android.externalstorage.documents/tree/primary%3ADownload%2Fetct 
popup_saved_xsq ~ )   �t prefer_original_audioq ~ t feed_update_threshold_keyt 0t brightness_gesture_controlq ~ t 
popup_saved_ysq ~ )  �t notification_colorize_keyq ~ t volume_gesture_controlq ~ t streams_notifications_networkt wifit enable_streams_notificationsq ~ t right_gesture_controlt none_controlt autoplay_keyt autoplay_never_keyt feed_show_future_itemsq ~ t prefer_descriptive_audioq ~ t (media_tunneling_device_blacklist_versionsq ~ )  �t content_languaget systemt enable_search_historyq ~ t default_download_threadssq ~ )    t show_meta_infoq ~ t "acra.legacyAlreadyConvertedTo4.8.0q ~ t key_theme_changeq ~ t themet black_themet preferred_open_action_keyt video_playert notification_slot_3_keysq ~ )   
t download_thumbnail_keyq ~ t default_video_formatt 
video_webmt linearq ~ t show_descriptionq ~ t key_main_page_changeq ~ t adjustment_step_keysq ~ #>�  t update_expiry_keysq ~     b��0t last_used_preferences_versionsq ~ )   t seekbar_preview_thumbnail_keyt &seekbar_preview_thumbnail_high_qualityt left_gesture_controlt none_controlt playback_unhook_keyq ~ t show_hold_to_appendq ~ t notification_slot_1_keysq ~ )   t acra.lastVersionNrsq ~ )  �t downloads_queue_limitq ~ t show_original_time_ago_text_keyq ~ t screen_brightness_keysq ~ #?Z�t peertube_selected_instancet 2{"name":"FramaTube","url":"https://framatube.org"}t use_inexact_seek_keyq ~ t show_age_restricted_contentq ~ t 6always_use_exoplayer_set_output_surface_workaround_keyq ~ t clear_queue_confirmation_keyq ~ t last_dl_type_videot last_dl_type_videot auto_queue_keyq ~ t playback_skip_silence_keyq ~ t night_themet 
dark_themet enable_playback_resumeq ~ t file_replacement_charactert  _t update_app_keyq ~ t default_resolutiont 1080p60t  playback_adjust_by_semitones_keyq ~ t downloads_max_retryt 15t content_countryt systemt last_orientation_landscape_keyq ~ t notification_slot_compact_0_keysq ~ )   t show_next_videoq ~ t downloads_storage_askq ~ t 
download_patht Qcontent://com.android.externalstorage.documents/tree/primary%3ADownload%2Fnewpipet list_view_modet listt cross_network_downloadsq ~ t allow_heap_dumping_keyq ~ t feed_fetch_channel_tabssq ~ w   ?@     t fetch_channel_tabs_videost fetch_channel_tabs_livet fetch_channel_tabs_tracksxt saved_tabs_keyt 1{"tabs":[{"tab_id":2},{"tab_id":3},{"tab_id":4}]}t storage_use_safq ~ t feed_use_dedicated_fetch_methodq ~ t show_image_indicators_keyq ~ t show_search_suggestionssq ~ w   ?@     t show_remote_search_suggestionsxt progressive_load_intervalt exoplayer_defaultt notification_slot_compact_2_keysq ~ )   t  start_main_player_fullscreen_keyq ~ t youtube_restricted_mode_enabledq ~ t playback_pitch_keysq ~ #?�  t file_rename_charsett CHARSET_MOST_SPECIALt notification_slot_2_keyq ~ .t enable_watch_historyq ~ t report_player_errors_keyq ~ t !ignore_hardware_media_buttons_keyq ~ t main_tabs_positionq ~ t disable_media_tunneling_keyq ~ t minimize_on_exit_keyt minimize_on_exit_background_keyt allow_disposed_exceptions_keyq ~ t !acra.legacyAlreadyConvertedToJsonq ~ t #preferred_open_action_last_selectedt video_playert use_external_audio_playerq ~ t import_export_data_patht �content://com.android.externalstorage.documents/document/primary%3ADocuments%2FSyncthing%2FBackup%2FNewPipe%2FNewPipeData-20230823_124323.zipt !feed_show_partially_watched_itemsq ~ t default_audio_formatt 	audio_m4at playback_speed_keysq ~ #?�  t notification_slot_0_keyq ~ �t show_play_with_kodiq ~ t 
seek_durationt 10000t peertube_instance_listt B{"instances":[{"name":"FramaTube","url":"https://framatube.org"}]}t servicet YouTubet stream_info_selected_tabt COMMENTSx

Settigs (new): (recreation)
> ```
�� sr java.util.HashMap���`� F 
loadFactorI 	thresholdxp?@     `w   �   Tt &scale_to_square_image_in_notificationssr java.lang.Boolean� r�՜�� Z valuexpt resume_on_audio_focus_gainsq ~  t use_inexact_seek_keyq ~ t tablet_modet autot show_age_restricted_contentq ~ t 6always_use_exoplayer_set_output_surface_workaround_keyq ~ t clear_queue_confirmation_keyq ~ t popup_remember_size_pos_keyq ~ t auto_queue_keyq ~ t show_original_time_ago_keyq ~ t night_themet black_themet limit_mobile_data_usaget 360pt enable_playback_state_listsq ~ t enable_playback_resumeq ~ t file_replacement_charactert ~t update_app_keyq ~ t default_resolutiont 1080p60t channel_tabssr java.util.HashSet�D�����4  xpw   ?@     t show_channel_tabs_livestreamst show_channel_tabs_videost show_channel_tabs_albumst show_channel_tabs_channelst show_channel_tabs_trackst show_channel_tabs_aboutt show_channel_tabs_shortst show_channel_tabs_playlistsxt downloads_max_retryt 15t content_countryt systemt notification_slot_compact_0_keysr java.lang.Integer⠤���8 I valuexr java.lang.Number������  xp    t streams_notifications_intervalt 14400t show_next_videoq ~ t downloads_storage_askq ~ t app_language_keyt systemt "use_exoplayer_decoder_fallback_keyq ~ t default_popup_resolutiont 720p60t show_higher_resolutionsq ~ t list_view_modeq ~ 	t cross_network_downloadsq ~ t use_external_video_playerq ~ t 
show_commentsq ~ t allow_heap_dumping_keyq ~ t notification_slot_compact_1_keysq ~ +   t feed_fetch_channel_tabssq ~ w   ?@     t fetch_channel_tabs_shortst fetch_channel_tabs_videost fetch_channel_tabs_livestreamst fetch_channel_tabs_tracksxt show_thumbnail_keyq ~ t storage_use_safq ~ t notification_slot_4_keysq ~ +   t feed_use_dedicated_fetch_methodq ~ t show_image_indicators_keyq ~ t show_crash_the_player_keyq ~ t prefer_original_audioq ~ t show_search_suggestionssq ~ w   ?@     t show_local_search_suggestionst show_remote_search_suggestionsxt feed_update_threshold_keyt 300t progressive_load_intervalt 64t notification_colorize_keyq ~ t notification_slot_compact_2_keysq ~ +   t  start_main_player_fullscreen_keyq ~ t youtube_restricted_mode_enabledq ~ t file_rename_charsett CHARSET_MOST_SPECIALt streams_notifications_networkt wifit enable_streams_notificationsq ~ t notification_slot_2_keysq ~ +   t right_gesture_controlt none_controlt enable_watch_historyq ~ t autoplay_keyt autoplay_never_keyt prefer_descriptive_audioq ~ t !ignore_hardware_media_buttons_keyq ~ t (media_tunneling_device_blacklist_versionsq ~ +  �t content_languaget systemt main_tabs_positionq ~ [...]

2023-08-30 20:39 UTC, Feuerswut commented
These are my old settings:

```
�� sr java.util.HashMap���`� F 
loadFactorI 	thresholdxp?@     �w      {t &scale_to_square_image_in_notificationssr java.lang.Boolean� r�՜�� Z valuexpt resume_on_audio_focus_gainq ~ t screen_brightness_timestamp_keysr java.lang.Long;��̏#� J valuexr java.lang.Number������  xp  up���t tablet_modet offt popup_remember_size_pos_keyq ~ t show_original_time_ago_keysq ~  t enable_playback_state_listsq ~ t limit_mobile_data_usaget 360pt channel_tabssr java.util.HashSet�D�����4  xpw   ?@     t show_channel_tabs_livet show_channel_tabs_albumst show_channel_tabs_videost show_channel_tabs_channelst show_channel_tabs_infot show_channel_tabs_aboutt show_channel_tabs_trackst show_channel_tabs_playlistsxt streams_notifications_intervalt 900t app_language_keyt det "use_exoplayer_decoder_fallback_keyq ~ t popup_saved_widthsr java.lang.Float��ɢ�<�� F valuexq ~ D4@ t default_popup_resolutiont 1080p60t show_higher_resolutionsq ~ t last_resize_modesr java.lang.Integer⠤���8 I valuexq ~     t 
show_commentsq ~ t use_external_video_playerq ~ t notification_slot_compact_1_keysq ~ )   t show_thumbnail_keyq ~ t feed_show_played_itemsq ~ t notification_slot_4_keysq ~ )   t youtube_visitor_datat kekt "enable_lock_screen_video_thumbnailq ~ t show_crash_the_player_keyq ~ t download_path_audiot Mcontent://com.android.externalstorage.documents/tree/primary%3ADownload%2Fetct 
popup_saved_xsq ~ )   �t prefer_original_audioq ~ t feed_update_threshold_keyt 0t brightness_gesture_controlq ~ t 
popup_saved_ysq ~ )  �t notification_colorize_keyq ~ t volume_gesture_controlq ~ t streams_notifications_networkt wifit enable_streams_notificationsq ~ t right_gesture_controlt none_controlt autoplay_keyt autoplay_never_keyt feed_show_future_itemsq ~ t prefer_descriptive_audioq ~ t (media_tunneling_device_blacklist_versionsq ~ )  �t content_languaget systemt enable_search_historyq ~ t default_download_threadssq ~ )    t show_meta_infoq ~ t "acra.legacyAlreadyConvertedTo4.8.0q ~ t key_theme_changeq ~ t themet black_themet preferred_open_action_keyt video_playert notification_slot_3_keysq ~ )   
t download_thumbnail_keyq ~ t default_video_formatt 
video_webmt linearq ~ t show_descriptionq ~ t key_main_page_changeq ~ t adjustment_step_keysq ~ #>�  t update_expiry_keysq ~     b��0t last_used_preferences_versionsq ~ )   t seekbar_preview_thumbnail_keyt &seekbar_preview_thumbnail_high_qualityt left_gesture_controlt none_controlt playback_unhook_keyq ~ t show_hold_to_appendq ~ t notification_slot_1_keysq ~ )   t acra.lastVersionNrsq ~ )  �t downloads_queue_limitq ~ t show_original_time_ago_text_keyq ~ t screen_brightness_keysq ~ #?Z�t peertube_selected_instancet 2{"name":"FramaTube","url":"https://framatube.org"}t use_inexact_seek_keyq ~ t show_age_restricted_contentq ~ t 6always_use_exoplayer_set_output_surface_workaround_keyq ~ t clear_queue_confirmation_keyq ~ t last_dl_type_videot last_dl_type_videot auto_queue_keyq ~ t playback_skip_silence_keyq ~ t night_themet 
dark_themet enable_playback_resumeq ~ t file_replacement_charactert  _t update_app_keyq ~ t default_resolutiont 1080p60t  playback_adjust_by_semitones_keyq ~ t downloads_max_retryt 15t content_countryt systemt last_orientation_landscape_keyq ~ t notification_slot_compact_0_keysq ~ )   t show_next_videoq ~ t downloads_storage_askq ~ t 
download_patht Qcontent://com.android.externalstorage.documents/tree/primary%3ADownload%2Fnewpipet list_view_modet listt cross_network_downloadsq ~ t allow_heap_dumping_keyq ~ t feed_fetch_channel_tabssq ~ w   ?@     t fetch_channel_tabs_videost fetch_channel_tabs_livet fetch_channel_tabs_tracksxt saved_tabs_keyt 1{"tabs":[{"tab_id":2},{"tab_id":3},{"tab_id":4}]}t storage_use_safq ~ t feed_use_dedicated_fetch_methodq ~ t show_image_indicators_keyq ~ t show_search_suggestionssq ~ w   ?@     t show_remote_search_suggestionsxt progressive_load_intervalt exoplayer_defaultt notification_slot_compact_2_keysq ~ )   t  start_main_player_fullscreen_keyq ~ t youtube_restricted_mode_enabledq ~ t playback_pitch_keysq ~ #?�  t file_rename_charsett CHARSET_MOST_SPECIALt notification_slot_2_keyq ~ .t enable_watch_historyq ~ t report_player_errors_keyq ~ t !ignore_hardware_media_buttons_keyq ~ t main_tabs_positionq ~ t disable_media_tunneling_keyq ~ t minimize_on_exit_keyt minimize_on_exit_background_keyt allow_disposed_exceptions_keyq ~ t !acra.legacyAlreadyConvertedToJsonq ~ t #preferred_open_action_last_selectedt video_playert use_external_audio_playerq ~ t import_export_data_patht �content://com.android.externalstorage.documents/document/primary%3ADocuments%2FSyncthing%2FBackup%2FNewPipe%2FNewPipeData-20230823_124323.zipt !feed_show_partially_watched_itemsq ~ t default_audio_formatt 	audio_m4at playback_speed_keysq ~ #?�  t notification_slot_0_keyq ~ �t show_play_with_kodiq ~ t 
seek_durationt 10000t peertube_instance_listt B{"instances":[{"name":"FramaTube","url":"https://framatube.org"}]}t servicet YouTubet stream_info_selected_tabt COMMENTSx
```

This is a recreation of these settings using the latest apk:

```
�� sr java.util.HashMap���`� F 
loadFactorI 	thresholdxp?@     `w   �   Tt &scale_to_square_image_in_notificationssr java.lang.Boolean� r�՜�� Z valuexpt resume_on_audio_focus_gainsq ~  t use_inexact_seek_keyq ~ t tablet_modet autot show_age_restricted_contentq ~ t 6always_use_exoplayer_set_output_surface_workaround_keyq ~ t clear_queue_confirmation_keyq ~ t popup_remember_size_pos_keyq ~ t auto_queue_keyq ~ t show_original_time_ago_keyq ~ t night_themet black_themet limit_mobile_data_usaget 360pt enable_playback_state_listsq ~ t enable_playback_resumeq ~ t file_replacement_charactert ~t update_app_keyq ~ t default_resolutiont 1080p60t channel_tabssr java.util.HashSet�D�����4  xpw   ?@     t show_channel_tabs_livestreamst show_channel_tabs_videost show_channel_tabs_albumst show_channel_tabs_channelst show_channel_tabs_trackst show_channel_tabs_aboutt show_channel_tabs_shortst show_channel_tabs_playlistsxt downloads_max_retryt 15t content_countryt systemt notification_slot_compact_0_keysr java.lang.Integer⠤���8 I valuexr java.lang.Number������  xp    t streams_notifications_intervalt 14400t show_next_videoq ~ t downloads_storage_askq ~ t app_language_keyt systemt "use_exoplayer_decoder_fallback_keyq ~ t default_popup_resolutiont 720p60t show_higher_resolutionsq ~ t list_view_modeq ~ 	t cross_network_downloadsq ~ t use_external_video_playerq ~ t 
show_commentsq ~ t allow_heap_dumping_keyq ~ t notification_slot_compact_1_keysq ~ +   t feed_fetch_channel_tabssq ~ w   ?@     t fetch_channel_tabs_shortst fetch_channel_tabs_videost fetch_channel_tabs_livestreamst fetch_channel_tabs_tracksxt show_thumbnail_keyq ~ t storage_use_safq ~ t notification_slot_4_keysq ~ +   t feed_use_dedicated_fetch_methodq ~ t show_image_indicators_keyq ~ t show_crash_the_player_keyq ~ t prefer_original_audioq ~ t show_search_suggestionssq ~ w   ?@     t show_local_search_suggestionst show_remote_search_suggestionsxt feed_update_threshold_keyt 300t progressive_load_intervalt 64t notification_colorize_keyq ~ t notification_slot_compact_2_keysq ~ +   t  start_main_player_fullscreen_keyq ~ t youtube_restricted_mode_enabledq ~ t file_rename_charsett CHARSET_MOST_SPECIALt streams_notifications_networkt wifit enable_streams_notificationsq ~ t notification_slot_2_keysq ~ +   t right_gesture_controlt none_controlt enable_watch_historyq ~ t autoplay_keyt autoplay_never_keyt prefer_descriptive_audioq ~ t !ignore_hardware_media_buttons_keyq ~ t (media_tunneling_device_blacklist_versionsq ~ +  �t content_languaget [...]

2023-08-31 09:55 UTC, TobiGr commented
That's completely strange, I am unable to reproduce this. Please send the database exports to `team[at]newpipe.net` and put a reference to this PR into the email.

2023-08-31 10:01 UTC, Feuerswut commented
I got you.

Import these settings and it will crash once you click on play in pop-up.

Kind Regards,

Am 31. August 2023 09:56:13 UTC schrieb Tobi ***@***.***>:
>That's completely strange, I am unable to reproduce this. Please send the database exports to `team[at]newpipe.net` and put a reference to this PR into the email.

2023-09-10 08:53 UTC, TobiGr commented
I removed the behaviour change and only kept the deduplication as requested by @AudricV

2023-09-18 09:05 UTC, AudricV requested changes
Almost good to me, thanks for everyone involved in the app part of these changes!

I found some issues, including ones which doesn't necessarily need to be done, such as formatting or Javadoc issues.

I also found that when the app is started directly with a channel URL, it shows briefly the default home page tab name, it was an empty name before these changes. Could this new behavior be reverted to the original?

2023-09-18 13:06 UTC, TobiGr commented on app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
> +    protected String channelName;
Those are states. They need to be accessible for IcePick. That means: not private or final. I added a comment

2023-09-18 13:28 UTC, TobiGr commented
> I also found that when the app is started directly with a channel URL, it shows briefly the default home page tab name, it was an empty name before these changes. Could this new behavior be reverted to the original?

@AudricV Do you mean this behaviour?

https://github.com/TeamNewPipe/NewPipe/assets/17365767/f22d8139-e8b1-4794-90d7-ddf2716d1587

2023-09-18 13:55 UTC, AudricV commented
Yes, I meant this behavior.

2023-09-18 13:56 UTC, TobiGr commented on app/src/main/res/layout/fragment_channel_videos.xml
> +
I was not able to test this removal, because I was lacking a channel to test this with.

2023-09-18 16:51 UTC, Feuerswut commented
Hi. I appear to have found another crash.

1. Installed latest app fragment (today)
2. Import database and settings
3. User App-setting dialog: 'Yes' to all 
4. Crash
The App won't load after.

provided System crash log (GrapheneOS latest stable/Pixel 6); this is not the App Crash Trace, It is generated by the System:

```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230805.001/2023090600:user/release-keys
package: org.schabi.newpipe.debug.channeltabs:994
process: org.schabi.newpipe.debug.channeltabs:acra
processUptime: 915 + 61 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create application org.schabi.newpipe.DebugApp: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6832)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2139)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:360)
	at androidx.preference.Preference.getPersistedBoolean(Preference.java:1975)
	at androidx.preference.TwoStatePreference.onSetInitialValue(TwoStatePreference.java:207)
	at androidx.preference.Preference.onSetInitialValue(Preference.java:1634)
	at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1607)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1330)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1345)
	at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:253)
	at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:173)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:350)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
	at androidx.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:188)
	at androidx.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:150)
	at org.schabi.newpipe.settings.NewPipeSettings.initSettings(NewPipeSettings.java:60)
	at org.schabi.newpipe.App.onCreate(App.java:87)
	at org.schabi.newpipe.DebugApp.onCreate(DebugApp.kt:12)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1282)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6827)
	... 9 more

```

As far as I can tell. This is the same crash that occurred previously when clicking the play in background buttons.

I will play around with the sandbox settings of Graphene to see whether they affect the app.

Here is a Video recreating the crash:

(Please wait one moment while I make a screen record.)

2023-09-18 19:52 UTC, TobiGr commented
@Feuerswut What backup are you importing? Is it an export that was made by a version from roughly three weeks ago? If this is the case, please note that those specific backups are incompatible with the current version because I removed the changed behaviour again and thus one internal value type is different.

2023-09-18 21:19 UTC, Stypox approved these changes
Thank you! I tested out all of the various things that were pointed out in the comments of this PR over time and found no regressions. There are still some things to improve to make channel tabs support perfect, but we can do it later, there is no need to do everything at once.
- The "Fetch channel tabs" feed setting misses the channel tab types that were added lately
- Shorts do not seem to be fetched in my feed, did we decide to just ignore those? We should probably show a warning if that's the case, and remove the entry from the  "Fetch channel tabs" setting
- Maybe we might want to merge the "Channels" tab with the "About" tab. Related channels are not really a content of the channel, but rather a metadata item, and as such they are used less frequently and in my opinion would fit better in its section in the "About" tab. This would also reduce the amount of tabs by 1, making scrolling simpler.
- I once got a layout issue on the channel header, where the banner would have a useless ~100px red padding above it. I can't reproduce this however. What I can reproduce instead are some 1px red bars on the sides of the banner.
- We could reduce the space used by header by moving the subscriber count in the subtitle and moving the avatar and the "Subscribe" button on top of the banner.
- In the end is it ok to just keep a doubly-tabbed layout for channels in the main page? Imo yes
- The shorts playlist workaround doesn't allow us to fetch shorts upload dates anymore, right? YouTube removed dates there too. Do we want to try with the Smart TV client as suggested [here](https://github.com/TeamNewPipe/NewPipe/pull/9182#issuecomment-1508851306)?

2023-09-18 21:19 UTC, AudricV approved these changes

2023-09-18 21:23 UTC, TobiGr approved these changes
We were not able to reproduce @Feuerswut's crash and assume that it was caused by an unsupported backup version. The goal is to merge this PR and get the changes into the nightlies to reach a broader testing audience.

2023-09-18 21:28 UTC, AudricV commented
> Shorts do not seem to be fetched in my feed, did we decide to just ignore those? We should probably show a warning if that's the case, and remove the entry from the "Fetch channel tabs" setting

No, that's because the extractor version is old and has the bug described in TeamNewPipe/NewPipeExtractor#1077.

> Maybe we might want to merge the "Channels" tab with the "About" tab. Related channels are not really a content of the channel, but rather a metadata item, and as such they are used less frequently and in my opinion would fit better in its section in the "About" tab. This would also reduce the amount of tabs by 1, making scrolling simpler.

I tend to disagree, as theoretically, a channel could have hundreds of related channels, which would fit better in a separate tab in this case.

> The shorts playlist workaround doesn't allow us to fetch shorts upload dates anymore, right? YouTube removed dates there too. Do we want to try with the Smart TV client as suggested [here](https://github.com/TeamNewPipe/NewPipe/pull/9182#issuecomment-1508851306)?

No, see TeamNewPipe/NewPipeExtractor#1077 for a discussion and reasons around that.

2023-09-18 21:46 UTC, merged