Pause player on internet disconnect and show toast
TeamNewPipe/NewPipe pull request #9245
Opened 2022-10-30 02:54 UTC by marevm

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- pauses video player when internet disconnects with ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
- disables error notification setting isCatchableException = true
- adds toast method to error util
- modifies play() to prepare() video if video is not prepared

#### Before/After Screenshots/Screen Record
- Before: 
![NewPipeError](https://user-images.githubusercontent.com/115518657/198860240-96410bf5-cd10-455b-9f31-86cec2dc34a6.png)

![NewPipeErrorMessage](https://user-images.githubusercontent.com/115518657/198859962-3937c34c-d355-484f-9eb6-b9a9ffb45f9d.png)

- After: 
![NewPipeNetworkToast](https://user-images.githubusercontent.com/115518657/198859966-6249837a-623c-49b2-92be-a89714143605.png)

#### Fixes the following issue(s)
- Fixes #8898

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-10-30 12:07 UTC, opusforlife2 commented
@marevm ANU student?

2022-10-31 17:29 UTC, AudricV requested changes

2022-10-31 17:29 UTC, AudricV commented on app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
> +
I don't think this is needed, using the `Toast` methods by themselves in classes which need them ensures that you apply the duration show you wanted.

This is a personal opinion, though.

2022-10-31 17:29 UTC, AudricV commented on app/src/main/java/org/schabi/newpipe/player/Player.java
> +                ErrorUtil.showErrorToast(context, "No internet connection available");
You must create a string ressource and reference it here, to allow translation of this message.

2022-10-31 17:29 UTC, AudricV commented on app/src/main/java/org/schabi/newpipe/player/Player.java
>              case ERROR_CODE_IO_NETWORK_CONNECTION_FAILED:
As you can see on [the JavaDoc of the error code](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlaybackException.html#ERROR_CODE_IO_NETWORK_CONNECTION_FAILED), using this error and show to the user that it doesn't have a connection in this case is not appropriate for all cases.

I recommend checking the network connection using the system APIs / compat/JetPack APIs if there are ones instead.

2022-11-02 19:44 UTC, opusforlife2 commented
> There should be an option 

Or, depending on what the timeout value is, the player could be set to pause just a little before that duration is completed, and keep trying to load until then.

2022-11-06 17:40 UTC, acrodemocide reviewed
Do we have any unit tests that should be updated for the new functionality?

2022-12-18 20:29 UTC, Stypox commented
> see the player paused every now and then having to click the play button manually

Have you read 8898? The player closes completely at the moment, so this is already better

2023-12-21 02:20 UTC, closed without merging