FR: Full width thumbnails aka card view mode
TeamNewPipe/NewPipe pull request #9310
Opened 2022-11-06 05:57 UTC by mahendranv

Rationale behind the feature:
When user go through videos, it's not possible to get enough info from title as content creators prefer to include details in thumbnails as such.
- Spec details in tech videos
- Movie names
- News headline
- so on

PR for https://github.com/TeamNewPipe/NewPipe/issues/6087
It has better experience when it comes to mobile portrait mode.

This PR adds new List view mode called `Card`. Behavior follows,
- A full width card with thumbnail size 16:9 ratio
- Two line full width title

#### Which screens include the new layout?
- Streams Feed/Trending/Channel details (list)
- Playlists in search and local playlist listing
- Streams inside local playlist

#### Minor code improvement:
Currently we have flags for `gridLayout`, `miniLayout`. Replaced the same with enum. Unified logic to identify the list mode resides in ThemeHelper.

#### Minor improvement for w800 devices
https://github.com/TeamNewPipe/NewPipe/issues/8412
Thumbnail size in grid is small for TV(and tablets). This PR includes a small tweak where size has been increased for w800 qualified devices. As opposed to seeing 6 small thumbnails in TV, user will see 3-4 of em now.

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #8412
- Fixes #6087

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-11-06 06:14 UTC, mahendranv commented
#### Streams
<img src="https://user-images.githubusercontent.com/6584143/200156765-390df70d-dad5-4a61-9f5f-baf6e8d72c9f.png" width="240"/>

#### Playlist
<img src="https://user-images.githubusercontent.com/6584143/200156825-cf208c2d-426b-446b-aa10-49f467b5798f.png" width="240"/>

#### Streams inside local playlist
<img src="https://user-images.githubusercontent.com/6584143/200156857-750dbff9-7bcd-4498-9a66-0f6b9e2384b7.png" width="240"/>


History is not changed since user does not explore new content in this screen and can recall the video by title and channel name. Also having multiple items on this screen will reduce number of scrolls user will make.

<img src="https://user-images.githubusercontent.com/6584143/200156980-76a58fff-eeec-423f-92a0-2041c60e89cd.png" width="240"/>

2022-11-06 14:56 UTC, mahendranv commented
> > Description of the changes in your PR
> > record videos
> > create clones
> > take over the world
> 
> Can someone tell me how to take over the world with Newpipe? i really need this feature
> 
> Also creating clones will be a nice addition to the app

Updated the PR description

2022-11-08 19:39 UTC, tvnmguy commented
Add YT channel's icon left to the video titles


![IMG_20221109_010544.jpg](https://user-images.githubusercontent.com/116799295/200659246-448610af-a06c-4e91-8ffd-62d43933ae11.jpg)

2022-11-09 02:19 UTC, mahendranv commented
@tvnmguy This is not implemented for two reasons
- The horizontal space taken by the avatar can be used to display more of the title. Uploader/Channel name is available below and user can long press the card to go-to the channel.
- Uploader avatar url is `nullable` and might not be available with all the providers. In such cases, we should plan for a placeholder

This can be a separate FR and based on votes/requirements it can be taken up.

2022-11-15 11:47 UTC, tvnmguy commented
Latest NewPipe release;

![IMG_20221115_165627.jpg](https://user-images.githubusercontent.com/116799295/201908885-581c56bd-5425-4a6f-b8f4-d73cf5a42f92.jpg)

PR Debug;

![IMG_20221115_165611.jpg](https://user-images.githubusercontent.com/116799295/201908995-0bf72bbb-9af3-4469-87e6-0e8440d09b6d.jpg)


{---------}, which is misbehaving in PR Debug.

•Completely missing both sides of the thumbnails.

![IMG_20221115_171332.jpg](https://user-images.githubusercontent.com/116799295/201911482-6faea27f-327f-4fae-8eba-a7590cf61d54.jpg)

•There is a gap in {---------} between each items (In latest release, there is no gap between them and also which was a two layer combination).

![IMG_20221115_171141.jpg](https://user-images.githubusercontent.com/116799295/201911131-55c469ee-ab2d-4441-a23e-fdc940af5a5c.jpg)

•In Newpipe release {---------} aligned next below to the refresh bar line.

![IMG_20221115_170837.jpg](https://user-images.githubusercontent.com/116799295/201910808-5e600627-79a7-4e45-a858-699a60c6510d.jpg)


Openion;

I think this card layout with proper arrangement of {---------} this would be better.

![session-2022-11-07-143118 (1).jpg](https://user-images.githubusercontent.com/116799295/201912079-c92a97c4-d53f-4696-86f1-29ff4f52c165.jpg)

![IMG_20221107_143223.jpg](https://user-images.githubusercontent.com/116799295/201912139-7536d542-dc0f-4b32-8d93-b77183d194b5.jpg)

![IMG_20221107_143356.jpg](https://user-images.githubusercontent.com/116799295/201912179-d3839f35-8940-4cfd-b6d1-fe100b4d30d3.jpg)

2022-11-16 05:34 UTC, mahendranv commented
@SameenAhnaf Above two can be done in a separate PR. Including them will make code review harder.

@tvnmguy I'll look into the double line issue

2022-11-30 18:18 UTC, mahendranv commented
@tvnmguy Fixed the gap between dashed lines and increased the gap on right/left in feed section. In other screens, the same edge to edge rendering is used.


| image | comments |
|-|-|
|![image](https://user-images.githubusercontent.com/6584143/204876671-e7fd786b-fe0d-4f88-89b7-2140728a8dec.png)| Here you can see the lines align / misalign. This is a draw back of using dashed lines, we cannot predict how OS renders two such lines.|

2022-12-01 10:03 UTC, tvnmguy commented
Other problems:

1: when press and hold;

(A) For Playlists: The alignment not correct in that area.

![IMG_20221201_151416.jpg](https://user-images.githubusercontent.com/116799295/205021555-59f9f936-ed3a-4404-94e5-aa0913642bb7.jpg)

(B) For Albums:

![session-2022-12-01-151103.jpg](https://user-images.githubusercontent.com/116799295/205021982-ee12516f-0246-438a-9227-0b7b1d898860.jpg)


2: I don't think this problem is associated with card view because NP stable has the same problem. Anyway I mention that one as well.

In search segment, the album doesn't show total number of videos on the cover. But it shows in bookmarked segment.

![IMG_20221201_153320.jpg](https://user-images.githubusercontent.com/116799295/205024475-c38efec5-f46b-4b41-ae62-236907965f8b.jpg)

![IMG_20221201_153307.jpg](https://user-images.githubusercontent.com/116799295/205024517-0a4d0d70-7b5a-494d-b298-4cd93f945b61.jpg)

2022-12-01 15:36 UTC, mahendranv commented
Making more customization specific to card layout will make the code-base prone to cosmetic errors and will break the existing generic UI paradigm. Also, it is not ideal to raise broader PR since code review won't have particular thing to focus.

2022-12-04 16:19 UTC, tvnmguy commented
@mahendranv 

What's your thoughts about this like card view👇

![IMG_20221204_214436.jpg](https://user-images.githubusercontent.com/116799295/205502475-7c825de2-d6b3-4d76-89fa-2c32b6ddf010.jpg)

2022-12-07 10:12 UTC, Drangonfly30 commented
Hello, I would like to ask why the thumbnail quality is low in Card view? Also the last proposed design by @tvnmguy looks nice.

2022-12-08 03:09 UTC, mahendranv commented
> So local playlists will preserve the list mode UI, right? Is that also the case for other playlists? A unified layout would make more sense imo.

@PassionateG1t Here you can see the screenshot. https://github.com/TeamNewPipe/NewPipe/pull/9310#issuecomment-1333516251

I made changes, but it doesn't make sense for playlist to have larger thumbnails. It just reduces the number of visible items.

Streams inside playlist, has a full width variant. You can find screenshot in first or second comment.

2022-12-31 21:30 UTC, Stypox commented
Mmmh, I think for consistency it would be better not to do per-screen customizations. If the user wants big thumbnails, then he will have big thumbnails everywhere. If he doesn't like big thumbnails, he can choose intermediate-sized ones (grid) or small ones (list). This also makes the code and the decision-making simpler. If in the future we find out this is a bad choice we can always change the type of some screen without issues.

> in history, we might not focus on thumbnail, rather title and number of items on screen is important.

You might say so, but maybe somebody else would disagree. If someone chooses big thumbnails because the channels they are subscribed to have more information in thumbnails, then the history will most likely contain videos from those channels and they would want to see big thumbnails there, too.

2023-01-01 15:47 UTC, mahendranv commented
@Stypox Except the history screen, others have full width cards now. I'll update the history screen sometime this week.

2023-01-06 23:00 UTC, mahendranv commented
@SameenAhnaf I think the above ticket is for keypad navigation, which we haven't covered yet. This one purely focus on larger / full width thumbnails.

2023-01-07 09:42 UTC, mahendranv commented
@Stypox  - Updated history screen to use full width card now.

@SameenAhnaf  - Yeah.. for TV UX, https://github.com/TeamNewPipe/NewPipe/issues/8412 and https://github.com/TeamNewPipe/NewPipe/issues/9635#issuecomment-1374128194 should cover most usecases. In this PR, we have increased the thumbnail size - this should slightly improve usability.

2023-01-09 07:20 UTC, tvnmguy commented
Implementation of 'You are all caught up' specifically for card view mode in subscription feed would be a nice addition.

Unlike other view mode, in card view mode view for total new feed items is not as great as the other view mode and need more scrolling. So implementation of 'You are all caught up' in subscription feed really helps to avoid infinite scrolling.

![img_2023_01_08_14_57_24.jpg](https://user-images.githubusercontent.com/116799295/211257242-3e870034-ab0d-4767-af3a-55337428a2c3.jpg)

![IMG_20230108_145131.jpg](https://user-images.githubusercontent.com/116799295/211257344-b0f48866-96f8-4368-a9ab-42ffbd1c82ab.jpg)


★ Inspired from Instagram mobile app

Ref;

https://user-images.githubusercontent.com/116799295/211257619-79285cfd-14fc-4d12-b2cb-1b0dd96a4dbe.mp4

2023-01-12 17:23 UTC, mahendranv commented
@SameenAhnaf  / @Stypox - Can you start the workflow?

2023-01-15 10:01 UTC, Stypox requested changes

2023-01-15 11:23 UTC, mahendranv commented on app/src/main/res/values-w820dp/dimens.xml
> +    <dimen name="video_item_grid_thumbnail_image_height">160dp</dimen>
For tablets and TV, this increases the thumbnail size.

2023-01-15 11:26 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +                }
@Stypox  Inlined comments, this ensures card is rendered end to end in all other places. Only for outline visibility this has been included.

Another way is to use background color variation to show new videos. It'll remove all the complexity about dotted lines.

2023-01-15 12:58 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
> +        final int result;
It is recommended by sonar to keep number of return statements under 3. So created a final result variable to cover all cases.
https://rules.sonarsource.com/java/RSPEC-1142

2023-01-15 12:58 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
> +        final int result;
It is recommended by sonar to keep number of return statements under 3. So created a final result variable to cover all cases.
https://rules.sonarsource.com/java/RSPEC-1142

2023-01-15 13:00 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/info_list/holder/StreamCardInfoItemHolder.java
> +    }
Created to provide interface if any customization is required in the future.

2023-01-15 13:24 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
>      public static boolean shouldUseGridLayout(final Context context) {
In **SubscriptionFragment**, only the Grid and List are supported now. Implementing full width mode won't benefit in this screen.

<details><summary>Screens</summary>
<p>

| List mode  | Grid mode  |
|---|---|
| ![image](https://user-images.githubusercontent.com/6584143/212543215-ad1cef58-ee8d-4a75-bba6-4b197d13fc31.png) | .![image](https://user-images.githubusercontent.com/6584143/212543254-85e30fd6-536c-4f3e-b9ce-ad6df8e992f8.png) |

</p>
</details>

2023-01-15 14:21 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
> +        final int result;
Let's ignore that and use `return` multiple times. It is simpler and more readable than setting a result.

2023-01-15 14:21 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
> +        final int result;
see above ^

2023-01-15 14:23 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +                }
Sorry, I'm not sure I understand. Do you mean that the dotted line would not be clearly visible in the card view mode?

2023-01-15 14:24 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
>      public static boolean shouldUseGridLayout(final Context context) {
Oh yeah, I missed that, you're right

2023-01-15 16:32 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +                }
This was an observation in the debug APK. With cards rendered edge to edge, the lines were not visible. So, added horizontal padding in feed page variant.

<details><summary>Images</summary>
<p>

| Without padding  | With padding  | With padding (dark) |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/6584143/212552741-3421b24a-8ed4-44e1-82a5-9b28036c98dc.png)|  ![image](https://user-images.githubusercontent.com/6584143/212552887-d0cc2790-d082-497b-b40c-7d737d8ee11b.png)  | ![image](https://user-images.githubusercontent.com/6584143/212553198-ca3c3650-9e76-49d0-93a9-602befeafe33.png) |
</p>
</details>

Also, these lines tends to have below artifact.
<details><summary>image</summary>
![image](https://user-images.githubusercontent.com/6584143/212553489-874a7268-0688-4994-9523-16d8e36117ff.png)
</details>

IMO, if we use a background color / unread red dot to highlight new videos, we can avoid some of the calculations done in this class.

2023-01-15 16:40 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +                }
Yeah, what I mean is, just add some 2dp padding to the thumbnail in the card item, no need to create custom code to do so programmatically

2023-01-15 16:43 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
> +                    result = MINI_STREAM_HOLDER_TYPE;
Done

2023-01-15 16:43 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/info_list/holder/StreamCardInfoItemHolder.java
> +    }
Done

2023-01-15 16:44 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
> +        final int result;
Replaced result variable with return statements and removed break.

`useMiniVariant` is the last if statement now

2023-01-15 16:45 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
> +        final int result;
Done

2023-01-15 16:58 UTC, mahendranv commented on app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
> +                }
Updated padding to 2dp

2023-01-15 17:02 UTC, mahendranv commented
@SameenAhnaf I'll raise a separate PR. And provide with mocks. 

> @mahendranv One more modification is required. #9555 is expected to add support for big thumbnails for channels in `Grid` view. IMO, subscriptions for `Card` view should be shown exactly as it's in that PR.
> 
> But channels in search results should be shown this way. Thumbnail should be in the middle of left side and description should auto-fit as required. ![IMG_20230114_185857](https://user-images.githubusercontent.com/79245641/212472956-ade63116-c785-4f0d-b695-475612af25e9.png)

2023-01-15 17:04 UTC, mahendranv commented
@Stypox  - Addressed review comments - pls start the workflow

2023-01-15 19:21 UTC, Stypox commented on app/src/main/res/values-w820dp/dimens.xml
> +    <dimen name="video_item_grid_thumbnail_image_height">160dp</dimen>
Maybe these are a bit too big, but let's see how user perceive it.

(leaving here some other plausible values I found)
```xml
    <dimen name="video_item_grid_thumbnail_image_width">208dp</dimen>
    <dimen name="video_item_grid_thumbnail_image_height">117dp</dimen>
```

2023-01-15 19:25 UTC, Stypox approved these changes
Code looks good to me. I tested on various devices with different sizes and APIs and even Android TV and it works well. Thank you!

2023-01-15 19:25 UTC, merged

2023-01-29 09:51 UTC, Stypox commented
Found [this comment](https://teddit.net/r/NewPipe/comments/10ifp3p/release_candidate_v0250/j5i1twz/#c) on reddit:

> Any way to get the smaller grid back? Using on an Android TV 5.1 and the humongous 3x2 grid makes navigation extra difficult. On 0.24, the grid is 5x2. Same for channel icons in subs. 7x4 grid vs 7x2 on 0.24. With 500+ subs, if I need to scroll with a remote, that's for a whole day of waiting. I have tablet mode forced on. (Not that it makes a difference.) (Honestly I'd prefer the subscription categories icons to be smaller too, like they were in 0.23. Even on the phone, these are needlessly large.)

So apparently some users perceive it this way. Maybe it's better to revert the part of this PR that makes thumbnails bigger, or choose some different values?

2023-01-29 16:09 UTC, Stypox commented
Well, considering the issue was originally raised because of small thumbnails on TVs, it wouldn't make much sense to make thumbnails on TVs smaller and tablet ones bigger

2023-01-29 20:43 UTC, Stypox commented
I think remote control can only go right, left, up, down. So if we mapped the "down" to "go down one page" we would have no way to "go down one row".

2023-01-29 20:49 UTC, Stypox commented
That would conflict with going to the next main page tab, wouldn't it?

2023-01-30 03:20 UTC, mahendranv commented
For TV, the normal layout and focusables won't help. Basic requirement is DPad accelerated smooth scrolling.

DPad recyclerview is a third party lib optimised for TV. You can see demo videos in the readMe.

https://github.com/rubensousa/DpadRecyclerView

It's still in Alpha. But worth try.

2023-02-11 07:07 UTC, mahendranv commented
@Angelk90 Card layout is targeted for Phone-Portrait mode where thumbnails will be too small. Ideally to give better UX, the grid layout should have customizable column count.