Improve ellipsising of comments text (in `NewPipeTextView`) (+ a simple slide open animation)
TeamNewPipe/NewPipe pull request #9544
Opened 2022-12-14 09:25 UTC by devlearner

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Before/After Screenshots/Screen Record

(to be supplied after CI completes ~the CI test runs seem to be a bit feeble these days~)

#### Fixes the following issue(s)

- Fixes #3610
- Fixes #4009
- Fixes #7334

_p.s._ I just realize afterwards that there used to be an `AnimationUtil` class which was ported to Kotlin extensions a while ago (by one of our great developers), the 'revival' of `AnimationUtil` was a pure coincidence and with all due respect unintended (but it also does a couple of things extra like keeping a list of running and trying to reuse old animators); probably need to ponder how to better integrate with the existing `animate(...)()` ktx's, but I'll just leave it as is in draft for now

_p.s.(2)_ I saw there're a couple of brilliant PRs in flight which also touch upon `NewPipeTextView`; I'll rebase this PR after they're merged (which I guess would be pretty soon)

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-12-14 17:06 UTC, opusforlife2 commented
Don't put technical details in a PR title.

2022-12-18 12:19 UTC, opusforlife2 commented
> ... amidst a cold night

You think you can manage finishing the PR before the gloom overtakes? xD

2022-12-18 15:59 UTC, devlearner commented
(oh I thought nobody actually reads the (extended) commit messages... xD ~that was an ode from literature class~)
I was thinking of wrapping this up and calling it a year, but we'll see ... xD

2023-01-01 18:15 UTC, Stypox requested changes
Thanks, the video detail fragment animation looks really nice! And also the ellipsizing process. This is a fast review just to understand better what your code does, I get it that it's still in draft state.
Would it be possible to split the two features into two separate PRs? That would make merging them easier and faster.
Did you write all of the code in `EllipsizeParams` and `AnimationUtil`, or did you take it from some system class? It seems really complicated for what it is meant to do :sweat_smile:.
Could you expand on how you fixed the comment problems? If I understand correctly you now paint the three dots on top of the trimmed text, to make sure the text is not trimmed at half a character and at the same time ensure the text does not overflow?

2023-01-01 18:15 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
> +            // legacy approach
I think you can safely assume that `binding.detailVideoTitleView` will always be instance of `NewPipeTextView`. Also, I wonder why the binding element is not already cast to that type. Maybe check if the text view has type `NewPipeTextView` both in the normal and the large-land layouts

2024-03-28 15:33 UTC, Stypox commented
Closing as there has been no recent activity, and we're going to rewrite this part with Jetpack Compose which is going to make things much simpler. Thank you anyway!

2024-03-28 15:33 UTC, closed without merging