Support audio only background for services only supporting video streams
TeamNewPipe/NewPipe pull request #9562
Opened 2022-12-17 20:27 UTC by evermind-zz

Some services may only have video streams and no separate audio streams available. This commit will add audio background playback support for those services. It uses the video source as audio source for background playback.

**Note** I think currently NewPipe is in no need to support this feature but maybe in the future. I use it in BraveNewPipe as some services do not support audio only streams. Would be great if it could be merged.
Thx

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- audio playback for services that do not support audio streams.
- use audio from video stream for audio only background playback

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2022-12-17 20:59 UTC, ShareASmile commented
Yes Thanks, it works on Such YouTube Link with only 360p Video
https://www.youtube.com/watch?v=cw2gJxNx6xs

My NewPipe usecase mostly is for background listening & on above Link when i long press into background it spews following error on current dev of NewPipe

## Exception
* __User Action:__ play stream
* __Request:__ Loading failed for [Pahle Nachiye [Full Song] Nachiye Gayiye Shagan Manayiye]: https://www.youtube.com/watch?v=cw2gJxNx6xs
* __Content Country:__ 
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux samsung/a22xnnxx/a22x:11/RP1A.200720.012/A226BXXU4AVB1:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.player.mediasource.FailedMediaSource$MediaSourceResolutionException: Unable to resolve source from stream info. URL: https://www.youtube.com/watch?v=cw2gJxNx6xs, audio count: 0, video count: 0, 1
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$3$org-schabi-newpipe-player-playback-MediaSourceManager(MediaSourceManager.java:432)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

2022-12-17 21:12 UTC, evermind-zz commented
great so NewPipe has also a use case for this PR

2022-12-17 21:28 UTC, AudricV commented
Note: I already made a fix for this bug in #8603.

2022-12-19 21:02 UTC, Stypox requested changes
Thank you! Code looks good to me. I tested and this seems to work fine, by switching to background from the play queue on the video provided by @ShareASmile. However, on that video, the background button is still hidden in the video details fragment. Could you fix that, please?

@AudricV can this be merged even though #8603 also fixes the same issue? If you think it's better to just finish off #8603 then maybe we could do that and avoid some rebasing issues.

2022-12-20 04:48 UTC, evermind-zz commented
> Thank you! Code looks good to me. I tested and this seems to work fine, by switching to background from the play queue on the video provided by @ShareASmile. However, on that video, the background button is still hidden in the video details fragment. Could you fix that, please?

I'd rather wait for @AudricV to comment. AudricV's  could best compare the different approaches. I think mine is more lower level meaning it is contained in AudioPlaybackResolver. transparently to upper layers.

2023-01-01 17:06 UTC, Stypox commented
@AudricV said #8603 will not be merged for a while (it's a draft atm), so for me it's fine to merge this PR before. Your changes will at some point be overwritten by #8603, but in the meantime this will solve some issues. Thanks!

2023-01-01 17:12 UTC, ShareASmile commented
> However, on that video, the background button is still hidden in the video details fragment. Could you fix that, please?

^^

2023-01-02 16:51 UTC, Stypox approved these changes
I tested again, also taking a look at the network inspector, and it seems to work well. Thank you!

2023-01-02 16:51 UTC, merged