Changed the What's New icon
TeamNewPipe/NewPipe pull request #9678
Opened 2023-01-13 15:39 UTC by Marius1501

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Changed the What's New icon 
- Now it has a Youtube-styling

#### Before/After Screenshots/Screen Record

![NewPipe2 – ic_whats_new xml  NewPipe2 app main  13 01 2023 16_37_10](https://user-images.githubusercontent.com/109673982/212359171-14e6736a-156b-494c-915d-bc6c063c4cfd.png)

#### Fixes the following issue(s)

- Fixes #2552

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2023-01-13 18:05 UTC, Stypox requested changes

2023-01-13 18:05 UTC, Stypox commented on app/src/main/res/drawable/ic_whats_new.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
This icon is called `subscriptions` [here](https://fonts.google.com/icons?selected=Material+Icons&icon.query=subscriptions), so please keep the original name for consistency

2023-01-13 22:43 UTC, tvnmguy commented
There is some changes needs;

[1]
![IMG_20230114_035633.jpg](https://user-images.githubusercontent.com/116799295/212432370-836b1a04-f499-4c00-9191-df2ecf68bb3e.jpg)
[2]
![IMG_20230114_035449.jpg](https://user-images.githubusercontent.com/116799295/212432444-dd42b449-1f33-4ef8-adb8-5bfcd1caaaf0.jpg)
[3]
![IMG_20230114_040437.jpg](https://user-images.githubusercontent.com/116799295/212432461-54e0392e-066e-4d23-a751-6731f239dec9.jpg)
[4]
![IMG_20230114_040832.jpg](https://user-images.githubusercontent.com/116799295/212432495-fbf0d2cc-17bf-40e4-a26a-052d088ab5b4.jpg)

2023-01-14 09:41 UTC, Marius1501 commented
@tvnmguy all the changes you mentioned are already in this PR except for the naming of the What's New and the Subscriptions section. Should we really rename these sections?

2023-01-15 14:04 UTC, Stypox commented
>  Should we really rename these sections?

No, "what's new" is a perfectly valid name. "Subscriptions" and "Channels" might be confused instead.

2023-01-15 14:11 UTC, Stypox approved these changes
Works, thank you!

2023-01-15 14:12 UTC, merged