Fixed a bug that caused the background player to stop working
TeamNewPipe/NewPipe pull request #9706
Opened 2023-01-20 09:40 UTC by Jared234

#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

The bug was caused by an incorrect comparison between the existing `PlaylistQueue` and the new `PlaylistQueue`. In the `handleIntent` method in the `Player` class, both are compared, and if they are considered equal, the existing `PlaylistQueue` remains unchanged (because why reinitialize the same queue?). However, the overridden equality check was incorrect, as it only checks if the streams are the same, without considering the `queueIndex`. By inserting this check, the bug is fixed and only if the queues are actually identical, the existing queue is not reinitialized anymore. 

#### Fixes the following issue(s)

- Fixes #9131 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2023-01-20 10:35 UTC, Stypox requested changes

2023-01-20 10:35 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
> +        if (other.getIndex() != getIndex()) {
This method is also used in other places where checking for the index is not wanted, e.g. in `VideoDetailFragment`. I would completely remove the `equals()` and `hashCode()` methods and create two new methods: `equalStreams(PlayQueue)` and `equalStreamsAndIndex(PlayQueue)`. Then the two methods can be called when needed, providing an easier to read code, and also preventing casting from `Object`.

2023-01-21 14:14 UTC, Jared234 commented
The "SonarCloud Quality Gate" failed. However, the "bug" it found cannot occur. If you take a look at the `equalStreams` method, you can see that it checks if `other` is null. Therefore, the `getIndex()` method can only be called on `other` in the `equalStreamsAndIndex` method if it is not null.  
Is there any way to ignore these kinds of issues? Or should I implement an additional check?

2023-01-28 20:55 UTC, Stypox submitted a review, later dismissed
LGTM, thank you!

2023-01-28 20:55 UTC, Stypox approved these changes

2023-01-28 20:56 UTC, merged