Remove wrong annotation
TeamNewPipe/NewPipe pull request #9872
Opened 2023-03-01 14:48 UTC by TobiGr

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The current release PR is failing the sonar lint quality quard. This PR removes the wrong annotation to make sonar lint happy:
> Do not use `@Nullable` in Kotlin; the nullability is determined by the Kotlin type `View.OnClickListener` **not** ending with `?` which declares it not nullable, contradicting the annotation

 (see https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&pullRequest=9869&id=TeamNewPipe_NewPipe&open=AYacpIb_J93zs3Jn_4eI)

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2023-03-01 18:00 UTC, AudricV commented
> ```
> > Task :app:runKtlint
> /home/runner/work/NewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt:9:1: Unused import (no-unused-imports)
> 
> > Task :app:runKtlint FAILED
> ```

You need to remove the annotation import too.

2023-03-01 18:49 UTC, Stypox requested changes

2023-03-01 18:49 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
> +        listener: View.OnClickListener?
Test

2023-03-02 22:02 UTC, TobiGr commented on app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
> +        listener: View.OnClickListener?
According to https://developer.android.com/reference/android/view/View#setOnClickListener(android.view.View.OnClickListener the listener can be null

2023-03-03 10:42 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
> +        listener: View.OnClickListener?
Yes, that's the point. That function shows a button, and a button without listener does not make sense.

2023-03-18 09:30 UTC, merged