Add audio language selector
TeamNewPipe/NewPipe pull request #9937
Opened 2023-03-18 14:57 UTC by Theta-Dev

#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Adds an audio language selector next to the video quality selector
- Default audio track is chosen by the configured content language. If no track matches, it defaults to English.
- New settings option: *Content* > *Prefer descriptive audio* (choose the descriptive audio track by default)

#### Before/After Screenshots/Screen Record

![language_selector](https://user-images.githubusercontent.com/19636565/226113370-20aa1e1d-3cee-4bc7-8b8c-078dcdfc5fe3.png)

#### Fixes the following issue(s)

- Fixes #5854

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

2023-03-18 16:49 UTC, AudricV commented
Thanks a lot! Here are some changes that I would suggest to do and that you need to do:

- For the audio settings you introduced, I would move the descriptive audio setting to `Video and audio`.
- For the language fallback you use, I would use the default locale instead of the English one, unless it creates some issues.
- For the audio track label, I am not sure if we should use the label set by the streaming service, as it creates localization issues. Track names provided by YouTube provides whether an audio track is an original or not, but that's only on recent videos, so we can't reliably extract this information on the label (and that's why I didn't added this property on the extractor, as I am not sure whether we should add it).
  
  Instead, I would use a string with the audio language translated in the app UI language and include the descriptive audio property if it is true with a string format (`%1s (%2s)` with `%1s` as the audio language and `%2s` as `descriptive`).

You need to fix the following behaviors:

- the background players (external and in-app) and video downloader ignore the settings you introduced;
- the downloader do not list the audio language for audio downloads;
- you should use the default audio language or the fallback language for video downloads at least, or better, if you want to do this in your PR and if other team members agree, add the audio selector below the video one: this would give flexibility to users. Someone else could always do the latter part :)
  
  This audio selector must be only present for demuxed streams and a message should be shown for muxed streams saying something like `An audio track should be already present in this stream`.
  The introduction of this message also raises the question to show all video streams and not merge video only and muxed video streams in the same list, as for instance, downloading a Mr Beast video in 720p with French audio track would not be possible in this case.

2023-03-18 18:24 UTC, AudricV commented
> The menu suggested in following screenshot could be shown before playing a video on external player.

That's not possible, as most of video streams are demuxed, so no audio track is available in them.

> Not sure if it is within the scope of this issue.
> Maybe, Newpipe should do the same.

Yes it is out of the scope of the issue and is not possible except on downloads, but this will probably require a lot of work.

2023-03-19 21:59 UTC, AudricV commented
Bug: the audio selection algorithm doesn't seem to take into account anymore the preferred audio format.

When selecting an audio track of latest Mr Beast's video for an external audio player with the M4A codec, I got the URL of a WEBM format (itag 251) where I should have got the itag 140.

Also, I don't know if that's intended or if you did changes since my comment about that, but no audio language is still shown in the downloader audio list.

2023-03-19 22:05 UTC, Theta-Dev commented
Hi @AudricV,
I am still working on the downloader, so I have not pushed it yet.
I'll look into the codec selection issue.

2023-04-02 00:36 UTC, Theta-Dev commented
Alright, I have everything implemented.

Do you know why the android tests time out?

2023-04-21 09:09 UTC, Stypox reviewed
> Default audio track is chosen by the configured content language. If no track matches, it defaults to English.

Shouldn't the default audio track chosen be the video's original lana

2023-04-21 09:55 UTC, Stypox requested changes
Things that should be tested before merging, on videos with various combinations of formats and languages. @Theta-Dev it would be great if you could provide a list of videos that have different features (e.g. no audio stream at all (i.e. only video streams with embedded audio), only original audio, descriptive audio, dubbed audio, all audio types in multiple languages, possibly not only from YouTube but from other platforms, too).
- downloading streams
- external player
- audio track menu both in the play queue activity and in the player

Thanks :-)

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
> +    int selectedAudioStreamIndex;
```suggestion
    int selectedAudioTrackIndex;
```

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
> -     * use a video stream as audio source to support audio background playback.
This comment shouldn't be lost

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
> +        player.reloadPlayQueueManager();
This part is also present in PlayQueueActivity. It's better to create a function on the player that combines these actions (maybe directly inside `setAudioTrack`, unless it's used in other places)

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/ListHelper.java
> +     * <li>If {@code preferOriginalAudio}: is original audio</li>
```suggestion
     * <li>If {@code preferOriginalAudio}: use original audio</li>
```

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/ListHelper.java
> +     * <li>If {@code preferOriginalAudio}: is original audio</li>
```suggestion
     * <li>If {@code preferOriginalAudio}: use original audio</li>
```

2023-04-21 09:55 UTC, Stypox commented on app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
> +            Arrays.fill(streamSizes, -2);
Maybe add a constant for `-2`

2023-04-21 20:37 UTC, Theta-Dev commented
Videos for testing:
no external audio: any Peertube or CCC video
original+descriptive audio: https://www.youtube.com/watch?v=TjxC-evzxdk
original+dub: https://www.youtube.com/watch?v=_8W2LIfl5RE
original+dub+descriptive: https://www.youtube.com/watch?v=Kn56bMZ9OE8
multilanguage (no audio stream types): https://www.youtube.com/watch?v=tVWWp1PqDus&t=42
multilanguage (with audio stream types): https://www.youtube.com/watch?v=YLt73w6criQ

2023-04-21 21:40 UTC, Theta-Dev commented
Okay, I applied the changes and updated the PR.

2023-04-30 18:04 UTC, AudricV requested changes
Thanks a lot!

Please address the following changes and try to avoid in the future that your IDE or yourself does formatting changes which make reviews harder.

2023-04-30 22:00 UTC, Theta-Dev commented on app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
> +        }
okay, I added the iso3-formatted language code in addition to the track ID

2023-05-01 22:40 UTC, AudricV approved these changes

2023-05-02 08:07 UTC, merged

2023-05-26 23:07 UTC, DebugKirby commented
All the testing apk links are 404'd
How do I get this apk?

2023-05-28 02:21 UTC, ShareASmile commented
As this code has been merged into dev branch. You can Try NewPipe Nightly builds:
https://github.com/TeamNewPipe/NewPipe-nightly/releases/tag/nightly-50

2023-06-22 10:15 UTC, TobiGr commented
I found a regression in the latest nightly which was most likely introduced by this PR: #10180

2025-08-10 15:57 UTC, 15968133193-commits commented
可以